### ISSUE TITLE
Feature Requests (2)

### ISSUE THREAD

**Issue by nitpicker02** [cheat-engine/cheat-engine#106]
==1
The List left of the Scan input area updates continuesly.
Can we have a checkmark that removes changed values from the results?
I find myself hammering the "Next Scan" button sometimes.

==2
Can we have an enumeration feature? Sometimes I'm down to 20 or so results and instead of drilling further down its faster to
add 1 to the first result value,
add 2 to the second result value,
add 3 to...
add 20 to the 20th result value, tab into the game and see what my value is, voila I've got the address.
I then save that address and set the others back to their normal value.

I'd like to have the adding bit done with one click.

Thank you for an awesome tool!

**Comment by cheat-engine** [comment]
1: I can already see people forgetting to uncheck that checkbox and then go into the game
but if I have time I'll see about writing a lua extention that adds this for you

tip: Assign a hotkey to next scan->unchanged value and just hold that key down continuously

2: Not sure, it's a bit of a specific thing.  You want this in the foundlist (list on the left), or in the addresslist (bottom)?

**Comment by nitpicker3** [comment]
win10 Anniversary Upgrade doesn't agree with Avira AntiVir. Had to reinstall the system and lost the browser safed passwords, I'm the requester.

1: Thanks for the tip! That works awesome, and yeah I can see forgetting to uncheck... 
For example with just the few buttons right now I often enough hit the "First Scan" button instead of the "Next Scan" and loose my progress...

2: I realise this is quite specific, but I don't think it's complex? I also in no way of form insist on it, I can quite comfortably live without it, but I thought it'd be a neat feature for other less qualified CE users too.
( I only use the main window and an occasional "what writes here" scan for pointers, but do not script, browse memory, or use the other no doubt great features at all, due to not understanding. )

To finally answer the questiong: I imagined that for the address list at the bottom.

Thank you for reading my request!

**Comment by BLACKROCKz** [comment]
1: I really like this one, also struggling with that quite often. but DB is right, people will forget disabling it so it shouldn't be a default feature of CE. Definitely looking forward to that extension though.

2: Whenever I scan for the character position in MMORPGs i end up with hundreds of results because there's that many children. the fastest way to find the parent is freezing half of all addresses and then check if you can move. if you can, you can delete all addresses you just froze. if you're stuck in place, you can delete all other addresses. repeat until only the parent is left. this way even large amounts of addresses are no problem to do manually. 
(In case you are looking for something like money you can do the same but instead of freezing half of the addresses you change them to a certain value.)

**Comment by cheat-engine** [comment]
added a repeat checkbox for unchanged scans
