### ISSUE TITLE
CE 7.1 - Pointer form is laggy

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1094]
This wasn't the case before, must be introduced by a recent change comparing to 7.0.

![ezgif-3-c2a88bdc767b](https://user-images.githubusercontent.com/14368203/72665081-25171400-39fd-11ea-9edc-63448703c0e2.gif)

**Comment by mgrinzPlayer** [comment]
You see this slowdown because there's disableautosizing enableautosizing missing.

And "generate errorlogs" (LazLogger) writes about it in log file.

Previously errorlogs were buffered, it changed here https://github.com/cheat-engine/cheat-engine/pull/948/files , logs are immdiately saved to errorlogfile.

Because now lazlogger does not use buffered output you can notice this slowdown.

For now, just disable "generate errorlogs".

**Comment by Symbai** [comment]
Where can I do this?

**Comment by mgrinzPlayer** [comment]
inside formAddressChangeUnit.pas

**Comment by Symbai** [comment]
Ah okay thought there was a setting or something
