### ISSUE TITLE
Memory Regions fails to solve a module

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1119]
WC3 Reforged, memory region does not resolve module path for some modules, in the screenshot below its the Warcraft III.exe:

![image](https://user-images.githubusercontent.com/14368203/73350554-29f18880-4285-11ea-8992-8ed65af289b6.png)

I also believe this is the reason why the pointer scanner returns ZERO results (despite them useless threadstack results) regardless of how deep I scan.

**Comment by cheat-engine** [comment]
The memory is green so that's ok. There is a module available

That it's not in the "Extra" field is just as it states, an 'Extra' , it's just the result of [GetMappedFilenameA](https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getmappedfilenamea) which apparently fails on this region for whatever reason.  But that's more a microsoft Windows bug then

**Comment by Symbai** [comment]
Could this be the reason why the pointer scanner fails? I only get threadstack results, no matter how deep (last try 7 levels, 9144 offset) I scan

**Comment by cheat-engine** [comment]
No, pointerscan just uses the modulelist which is available.
But in this case the pointerscan fails because it uses it's static memory as dynamic memory (It never allocates memory, it puts it all in it's preallocated memory).  Tell it to not stop scanning after it finds a static. And hope it doesn't encode the pointers like it does it's other values (rot12 or so)

**Comment by Symbai** [comment]
Thanks for the tip, this works much better (and takes much, much longer, lol)
