### ISSUE TITLE
kernel speed hack?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1127]
_KUSER_SHARED_DATA

A question that deviates from the subject, why does the speed hacker need to inject a DLL into the game? It is sufficient to use a driver to modify the time-related members of KUSER_SHARED_DATA.

Is it possible to speed hack if I change the kernel structure without injecting the DLL?

DBVM_SPEEDHACK Cause Computer to freeze

Injection speed hack detects hooking

Can I increase the speed by manipulating the _KUSER_SHARED_DATA structure?

**Comment by cheat-engine** [comment]
because you need a driver to do it without a dll.  Also, you can tell ce to manual map dll's into a process instead(always forceload modules)

dbvm speedhack works for me, what kind of freeze are you experiencing ? Did you set the speedhack speed to 0? Because that will freeze yes. (Windows like's it's animations too much and doesn't allow you to skip them)
If too high, then your screensaver/blanker will turn on. Adjust that timer or disable it completely

Also, while _KUSER_SHARED_DATA  likely can be used to adjust simple things like gettickcount, it won't affect QueryPerformanceCounter which is more often used in games (calls rdtscp)
