### ISSUE TITLE
CE Server Window Version?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#128]
It's an old idea

Someone is already trying to implement

C# Source Code Someone is only implementing RPM in the source being implemented

http://www.unknowncheats.me/forum/downloads.php?do=file&id=18572

https://www.unknowncheats.me/forum/general-programming-and-reversing/193813-ceserver-windows-x64-remote-scan-cheat-engine-incomplete.html

Are you planning to add a version that uses CE SERVER network scan on Windows?

**Comment by remizovm** [comment]
Hello, @kitty8904! I'm working on the dirty version of the port right now, and I'm using MSVS. I can't say when I can actually finish the work due to some specific bugs (for example, a bugged zlib library source not being compiled under windows without some manual fixes). I'm kinda new to github and the opensource so the main problem for me is in sharing - I'm working locally. What is the preferred way? Should I make a fork or should I finish firstly and make a pull request? Thanks for the possible help.
