### ISSUE TITLE
Tools for unknown value searching

### ISSUE THREAD

**Issue by ShadowFoxNixill** [cheat-engine/cheat-engine#1288]
I have a couple suggestions to make searching for limited sets of unknown values easier:

* The ability to assign a name to any value (which lasts for one search)
* The ability to use a name within a search
* A "New value" search condition, which ignores any value already seen (for memory purposes, this could possibly be limited only to named values)
* When you find a matching memory address, the ability to view what values were assigned to the names you picked

I'll provide an example workflow as a child comment.

**Comment by ShadowFoxNixill** [comment]
What I'm trying to accomplish right now that would use this is searching for the power-up memory address in Lego Racers 2.

At the start of a race, the racer isn't holding any power-ups. So I'd do a search for an unknown initial value, and name that value "Nothing".
![empty item orb](https://user-images.githubusercontent.com/1627071/85925071-224e0400-b864-11ea-9d17-c2b348ca49d6.png)

I could do a couple more scans for an "Exact value", with the value "Nothing", until I hit an item orb. After it's done randomizing what item I have, I see this:
![disc item](https://user-images.githubusercontent.com/1627071/85925141-778a1580-b864-11ea-9dad-4cbbe1006d4c.png)

So I'd set the scan to be a "New value" and name it "Disc". Then I could do a couple more "Exact value": "Disc" scans until I fire it, then go back to "Exact value": "Nothing". Then I'll hit another item orb...
![drill item](https://user-images.githubusercontent.com/1627071/85925173-abfdd180-b864-11ea-989d-54071e962d75.png)

Then I'd search "New value" named "Drill", search for that a couple times, cause I still don't know what the value currently is but I know it's not "Nothing" or "Disc". After I launch that and hit another orb...
![twister item](https://user-images.githubusercontent.com/1627071/85925200-dbacd980-b864-11ea-909e-7195c7d3c87e.png)

"New value" named "Twister". Search that a couple times. Fire it. Search "Exact value": "Nothing" a couple times. Find another item...
![drill item again](https://user-images.githubusercontent.com/1627071/85925227-0139e300-b865-11ea-98f0-a7411550e808.png)

Now I can search for "Exact value": "Drill". I repeat this process until I narrow down the address. When I pick one, I then view the values of the names, write them down elsewhere, and just search using those actual values the next time.

**Comment by cheat-engine** [comment]
Use saved scans. They are valid for a sibgle scan session (between first scan and new scan). You can name them as well.
So first do an unknown initial value and save it as "Nothing"
then get a powerup (e.g disc) and do a changed value scan and save that as "disc".
do a few unchanged value scans inbetwern and then get a new powerup (e.g drill) and scan for changed value. Then save as "drill"
repeat unchanged a few more times and get a new powerup (e.g twister)
do a changed value scan and save as "twister"
do a few more unchanged value scans and pickup a new powerup (e.g drill)

now the tricky part:
since you already have the scan saved for drill you can check the box "compare to saved scan", and select "drill"
then do an "UNCHANGED VALUE SCAN" as you are comparing the current memory state to the saved state of "drill"
the results left will have the same value as when your powerup had the drill value the first time

**Comment by ShadowFoxNixill** [comment]
Alright, saved scans solve the first two bullets and probably the last as well. How about "value not seen in any saved scan"?

**Comment by ShadowFoxNixill** [comment]
Wait, that's just a "changed value" compared against every saved scan, ye? That's not as helpful for the inverse ("it's one of the saved values but I don't know which") or for rapidly changing values, but for now I don't need such functionality.
