### ISSUE TITLE
Is it a bug or a spec?

### ISSUE THREAD

**Issue by DhaosCollider** [cheat-engine/cheat-engine#1488]
![164307](https://user-images.githubusercontent.com/72247447/108820796-0c196300-7600-11eb-9da0-b96e478334d5.png)
If this Confirmation occurs and the symbol is registered in the memory allocated by the script, cannot re-enable the script.
Is it a bug or a spec?

I prepared a script for verification.
[Tutorial-x86_64.zip](https://github.com/cheat-engine/cheat-engine/files/6027900/Tutorial-x86_64.zip)

Here's what I did.
1. Enable the script.
2. Kill the tutorial process.
3. Reattach the tutorial process and pass the Confirmation.
4. Get an error. <<step2_ptr was supposed to be added to the symbollist, but it isn't declared>>

**Comment by cheat-engine** [comment]
half-spec, half-bug as a result of not executing the disable section

you do not declare step2_ptr as a label. This causes CE to guess what it is, and since on the second run there is a symbol named step2_ptr, it assumes it's an address specifier and not a label, and addressspecifiers can not be registered as symbols

(And add to that that the dq 0 after step2_ptr:  is going to be written to the old memory address)

**Comment by DhaosCollider** [comment]
I understand, thank you.
