### ISSUE TITLE
Why Would You Put Malware In CE

### ISSUE THREAD

**Issue by TTVToastyTim** [cheat-engine/cheat-engine#1849]
How Do You Sleep At Night You Piece Of Crap

**Comment by TTVToastyTim** [comment]
CE Is "Open Source" Yet It Has Malware/Spyware/Adware/Trojan! Yet I'm Asking Again How Do Sleep At Night?

**Comment by cheat-engine** [comment]
because you can click on ignore and then not get it.
But I doubt you have even looked at it, and just go of what a product, that makes money from fearmongering, tells you.

But if you're too scared, you can of course get the [Patreon Version](https://www.patreon.com/posts/cheat-engine-7-3-54898257) .  It has no optional download offerings. Of course, there's a pretty big chance that your AV will still complain as it's called Cheat Engine, and according to some AV's(e.g malwarebytes) people only play games the way the developer meant it, and they would never play with cheats, so it's being marked as unwanted
