### ISSUE TITLE
Malicious

### ISSUE THREAD

**Issue by z0mbiesrock** [cheat-engine/cheat-engine#209]
Is Cheat Engine **TRULY** safe to use? [Many antivirus scanners detect it as malicious.](https://www.virustotal.com/en/file/9f498954b628b7cd9989a4ee2339601cfcbb58c8a32bfa2d0c8bc2adbd1d90ae/analysis/1499116420/)

**Comment by FreeER** [comment]
yes. Is that good enough to satisfy you? if so then why did you waste time scanning it? If not what more do you want? The code's available go look at it.

Anyways, to be nice:
There are many more scanners that don't and of the few that do most of them say something along the lines of
"PUA" - potentially unwanted application, potentially unwanted, CheatEngine, Hacktool, or, PUP (potentially unwanted program)

not exactly _malicious_. Most of those are probably from the ad stuff packaged in the installer which you can opt out of, or you can simply download the non-installer version if you go to the downloads page.

**Comment by secretclean** [comment]
Yeah, how DARE you besmirch the adware program that you can opt out of but is contained in the installer! Let me go a step further than the previous pretentious tool and call you an insolent mouth-breather for daring to ask such a question. So what if Windows blocks the installer by default and it tests positive for adware on multiple antivirus programs, just don't download THAT version.

Gall!

**Comment by FreeER** [comment]
@secretclean name 3 installers that you've used recently without something you needed to opt out of. It's ok, I'll wait....

Yeah. Beyond that, did you think about why else an antivirus program might flag something doing essentially the same kind of things malicious programs do, injecting code into another process, reading another process's information, changing the data? In this age of computers where computer literacy is the new "learn to read" and you can't really use the web without using a search engine, did you/they bother to see if anyone else asked the exact same question before or look for other versions that might be clean? Should every newbie who comes along and wastes someone's time to get the same answer regurgitated back to them get treated with kid gloves so they don't get scared off from the world of cheating on games and assembly code or get a response that reminds them that they could have found the answer theirselves or that the question is bordering on stupid? I think my opinion on the matter is obvious.

Imagine people coming up to you and asking if it's really safe to drive a car because there are a bunch of stats that say it's dangerous... day after day, year after year, imagine all these people keep asking if it's safe to drive a car after there have been numerous reports stating that it is safe when you have a driver's license and know what you are doing. I'm sure it's not a perfect analogy but its the first that came to mind for me.

**Comment by OscarOG** [comment]
@FreeER 
CoSMOS installer, Visual C++ installer, GIMP installer.
Why do you need to include unwanted programs in the installer? If i need them i´ll download it.

**Comment by n-newton** [comment]
Or y'know, people could just stop bundling crapware in their installers, i mean really, it serves no purpose at all...
And iirc, thats one of the reasons people stopped using/trusting sourceforge back in the day.

Anyways nevermind me, just passing through...

> or you can simply download the non-installer version if you go to the downloads page.
Doesn't exist anymore either.
