### ISSUE TITLE
CheatEngine Adware

### ISSUE THREAD

**Issue by ikonic-kyber** [cheat-engine/cheat-engine#2105]
Okay so, I understand that Cheat Engine itself isn't infected or compromised but the installer from cheatengine . org is being quite suspicious. When installing Cheat Engine, it appears that different executable files are dropped into AppData/Local/Temp, which then they are executed and start trying to edit the Windows registry. These files are created at the end of the CE installation, regardless of whether you opt out from the offers or not. I ran the installation twice to see, and two separate, different programs were executed after creation.
So I decided to check these two programs on Virus Total, and it appears both are detected as adware and other such things.
If I opt out of these offers, why is it that adware is still dropped and then executed?

**Comment by cheat-engine** [comment]
which specific registry edits are they?

ceregreset and fixwindows both access the registry and are picked up as malware by different AV's

and inno setup itself will register the ct file extension and disable some anti cheat autolaunch which would block CE from running

**Comment by protosam** [comment]
@cheat-engine distributing installers with anything other than the desired software is unaccepted these days I urge you to cease the behavior and remove the binaries.

While I can understand and even empathize with the desire to make economically viable products; my empathy ceases at malicious distribution of software. The people that this will be installed for are people who unwittingly doing so. The practice isn't just a morality issue or a business issue, but is it in fact a violation of the Computer Fraud and Abuse Act (CFAA); a law that Github and Patreon are both liable to.

To make it clear, I'm going to give this about a month or so to be corrected and if it's not, I'll be spending my hard earned dollary-doos on legal recourse to protect the technologically disinclined on this matter.

I hope you understand and I hope you do the right thing.

**Comment by protosam** [comment]
Less than 15 minutes of digging and it is very clear that these users are incapable of agreeing to any type of EULA for this type of monetization.

The type of user most commonly attracted to this software is also going to be children. 

Going to leave this here, I think I've made my point and hopefully wont have to return with a big stick to choke the money pipes.

**Comment by protosam** [comment]
> You can dismantle the setup and get rid of the adware, alternatively there leaks of the clean setup from Patreon you can also use, and yes this behaviour is unacceptable.

People should actually just compile it from source.

**Comment by cxtal** [comment]
> To make it clear, I'm going to give this about a month or so to be corrected and if it's not, I'll be spending my hard earned dollary-doos on legal recourse to protect the technologically disinclined on this matter.

Cool stuff, Kevin. We are so fortunate to have people like you around. So, that was in July 2022, now it is February 2023 which, carry the two, hmm, right, is much more than one month since you have extended your ultimatum. CE is still going on. What happened and how much did you spend? Were you joking?

**Comment by protosam** [comment]
> Cool stuff, Kevin.

Does insulting people make you feel good about yourself?

**Comment by CamilleHbp** [comment]
@cheat-engine You are making 11k/month on Patreon. 
<img width="317" alt="image" src="https://github.com/cheat-engine/cheat-engine/assets/11173924/a35e50aa-373a-416b-b121-e522f721f3b6">

When will you get rid of this malware in your installer process? You clearly don't need it to make money since the Patreon is successful. I could understand keeping the adware/malware while you check if voluntary donations are sustainable.

But now you have seen it works. There is NO NEED to keep the adware except for greed and avarice at the expense of those not savvy enough who will install the adware by mistake. Because no one will install it voluntarily. 

I can build from the source fine but most people can't/won't. You should really be shamed of yourself for this practice that was already shady from corporations 20 years ago.

I know I'm in the minority but I will build the sources myself and you will never get a cent from me as long as this practice continues.

**Comment by ComedyCenterAudience** [comment]
Simply depressing how he still didn't do anything about it
