### ISSUE TITLE
Help. multiple search available?

### ISSUE THREAD

**Issue by Drui7** [cheat-engine/cheat-engine#232]
How can I do a search at once under several conditions? 
for example: less than 4, not equal to 2, greater than 0, has changed. 
like that: x<4 && x!=2 &&  x>0 && x.IsChanged == true;
but so to write it once and run the filter, rather than filter 4 times.

for example, the data on which the search is being conducted can be tens of gigabytes, it would be very long to search 4 times for such a volume, as compared to searching many conditions once.

if such a functional is, then I did not find this possibility in the teaching material. excuse me for this and for English from Google translator.

**Comment by paulogdm** [comment]
This is not an issue, it is a question and should be aksed on the forums!

**Comment by Drui7** [comment]
@paulogdm ok, please add a way to search for the required values by entering the command in the input line of the type that I wrote above. and in the drop-down list where "group search, unknown value, etc.", there add "search by the entered formula".
now it does not sound like a question.

**Comment by FreeER** [comment]
Why not just pick whichever one will filter out the most results, CE does let you search for between 2 values, eg. 0<x<4. If your previous result was outside that range the "isChanged" search is implied since it wouldn't be inside the range if it didn't change.

**Comment by Drui7** [comment]
@FreeER you understand that this was a simplified example?
as already written at the top, such a search is much faster than searching several times. saving time, memory and computing power (and hence electricity).
say, the value lies ((1 <= x <= 10) or (x> 100)) and (changed or x! = 5)) or x == 45. (it can be complicated indefinitely).
the point is that if I know in advance as many parameters as I can, the more accurately and quickly I can find the answer, if there is such a functional.

the program already has everything for this, you just need to add a "search by formula" drop-down list and write a handler for this formula, and tell the users exactly which format you need to enter certain conditions.

at the moment such a handler already exists. when I look for a sequence (for example 4 bytes with a value of 10, then 4 bytes with a value of 5), then I just select "group search" and enter "4:10 4: 5" (without quotes).

**Comment by cheat-engine** [comment]
Though custom type isn't designed for it, you can use that
example: use as custom type (lua)
```typename="MyFormula. Scan for 1" --shown as the typename in ce
bytecount=4  --number of bytes of this type
functionbasename="customvaluetype"

function customvaluetype_bytestovalue(b1,b2,b3,b4,address)
  local v=byteTableToDword({b1,b2,b3,b4})

  if (v>12) and (v%6==0) and (v<100) then
    return 1
  else
    return 0
  end
end

function customvaluetype_valuetobytes(i,address)
  error('not usable')
end
return typename,bytecount,functionbasename
```

then scan for the value 1
once the scan is done (someday) rightclick the addresslist and choose display type to the type you wish

**Comment by FreeER** [comment]
> as already written at the top, such a search is much faster than searching several times
Can you prove that? If you can filter out 90% with a simple x < 5 search, 94% with a 0 < x < 5 search and 95% with a complicated 5 part search (which in the worst case could result in every address needing all 5 checks done instead of just 1 or 2), you're probably better with the simpler search that removes most of the false results and then you can narrow down the few remaining results very quickly with a couple more searches.

If you've done all the work to figure out very specific information you can probably use an AOB scan or a code injection that copies the address to find the value you want much more quickly than any complicated multi-part scan over the entire process's memory.

Anything can be complicated indefinitely, that does not mean it has to be let alone that it _should_ be.

"at the moment such a handler already exists. when I look for a sequence (for example 4 bytes with a value of 10, then 4 bytes with a value of 5), then I just select "group search" and enter "4:10 4: 5" (without quotes)." - this is actually quite different if you take the time to look at the code behind it. If you think I'm wrong then feel free to prove it by quickly implementing it yourself and creating a pull request (thanks github for existing... cause, you make that pretty easy to do).

I can't think of a single time that I've ever needed to do any searches more complicated than what you initially proposed for the same value/address and 99.9% of the time I didn't even want that.


I'm not saying it won't be done, I don't really contribute code and I'm certainly not the only person who could regardless. Mostly just trying to figure out if this is something that makes any real sense or just something where you got the idea and now feel like you have to defend it even if it doesn't make as much sense as you originally thought.

**Comment by Drui7** [comment]
@cheat-engine it's fine. but such a record is much longer to do than just select "search by formula" to enter in the line, for example, (x! = 0 && x! = 15) OR (x.Changed).
I'm not saying that everyone should use this way, just in some cases this method would be more convenient than multiple checks.

@FreeER if you need even more sense, here's an example: enter "x> 2 and x! = 5 and x! = 20 and x changed", then click "search" much faster.

now you need to do this:
0. select "equal"
1. tick "no"
2. Enter 5
3. wait for the search
4. Enter 20
5. wait for the search
6. Remove the tick "No"
7. select "more"
8. Enter 2
9. choose "changed"
10. wait for the search
11. get an answer

in the search for the formula:
0. select "search by formula"
1. Enter "x> 2 and xi = 5 and xi = 20 and x. Changed"
2. wait for the search
3. get an answer

**Comment by FreeER** [comment]
@Drui7 I don't care about the time it takes to input everything since that's fairly trivial (assuming no physical disabilities that make simply using a computer difficult) especially when searching tens of gigabytes of data. If the actual scan time isn't affected by much then it's not significantly better.

In your last example you could probably just search for x > 2 and then manually pick out the addresses you 
 care about from what's left, assuming that your original multi-search would get you less than, say, 300 results that you could have easily picked your value from.

Regardless. I feel like this discussion has no where to go at this point. You could argue that input time does matter and I could argue that it doesn't but nothing significant could be stated to really change each others opinion and you've already gotten an answer telling you how it's possible to do it :)

**Comment by cheat-engine** [comment]
you can now do `value>2 and value~=5 and value~=20 and value~=previousvalue`
