### ISSUE TITLE
Feature Suggestion: Menu listing all created hotkeys

### ISSUE THREAD

**Issue by cvionis** [cheat-engine/cheat-engine#2475]
If I want to view or manage the hotkeys I've created for a particular game, I have to remember which records I've created hotkeys for and go through each record's list of hotkeys one by one using the "Set hotkeys" option. It would be convenient to have an option that opens a menu listing all the hotkeys created for the current cheat table, allowing the user to manage existing hotkeys or create new ones.

**Comment by DhaosCollider** [comment]
I tried to do it in Lua.
Add "Hotkey Info" to the menu and click on it to output info about memory records for which hotkeys have been set.

![125608](https://user-images.githubusercontent.com/72247447/217716564-0f96815c-f679-4547-8cd0-9338e59f0a9b.png)
![31635](https://user-images.githubusercontent.com/72247447/217716573-9f6b38ac-afc8-4ef2-abc6-ead2a9c63079.png)

lua file: [outputHotKeySettings.zip](https://github.com/cheat-engine/cheat-engine/files/10693473/outputHotKeySettings.zip)
Required that you use Cheat Engine 7.2 or later because used "AddressList['description']".
Its recommended to throw lua file into CE's autorun folder.
Note: Used "HotkeyInfoItem" (TMenuItem) as a global.

**Comment by DhaosCollider** [comment]
An improved version was submitted to CEF.
[https://forum.cheatengine.org/viewtopic.php?p=5783013#5783013](url)

**Features:**
- Add Hotkeys menu
![205457 - コピー](https://user-images.githubusercontent.com/72247447/217815391-45df35ed-1e98-475a-9652-2b1b7cd3d57f.png)
- View Hotkey list
![204732 - コピー](https://user-images.githubusercontent.com/72247447/217815472-d7dfd67f-3703-4763-81e2-06d44f66c55e.png)
and once selected, invoke the target hotkey form.
![212533 - コピー](https://user-images.githubusercontent.com/72247447/217815583-a7840edc-8f88-4471-8ae1-6ba797f572d5.png)
- Clean all Hotkeys

**Comment by cvionis** [comment]
Finally got around to checking out the script. It works perfectly so far. Thanks!
