### ISSUE TITLE
[Question] Is Lazarus the only way to properly set up CE7.5 without silent installs?

### ISSUE THREAD

**Issue by LOxAzuli** [cheat-engine/cheat-engine#2621]
I had to resort to Lazarus in order to Safely set up CE, but why? I have had no other issues with previous CE versions before this, but when I install the executable by itself, an unknown program somehow finds its way onto my main drive (when I installed it on a separate drive) and triggers both my antivirus and malware scanners, tripping as "bloatware". I don't know if the current release is unsafe, or if this is intentional, but I kind of want to know what's going on (especially considering all the concern about the current version).

**Comment by fade2gray** [comment]
> I had to resort to Lazarus in order to Safely set up CE, but why?

Because you are a lazy reader?

![installer](https://github.com/cheat-engine/cheat-engine/assets/1332009/21c806e9-5e02-4e9d-8071-3192c27a5d06)

**Comment by Dijosto** [comment]
The installer can pop up as potentially unwanted software because of the adware it can install if you blindly click through accept.

**Comment by Arkevorkhat1** [comment]
Fade, referencing his own comment, refuses to actually acknowledge that regardless of the presence or absence of a decline button, this is still nothing more than a cash-grab because the main dev can't hack it in the real world due to only knowing dead languages. Who the fuck programs in *pascal* anymore? I'll tell you, fucking nobody except this clown.
