### ISSUE TITLE
Do we have Mac version for 6.7?

### ISSUE THREAD

**Issue by bournejason** [cheat-engine/cheat-engine#277]
Excuse me for filing this new issue, I just want to know if there is a Mac version for latest release? Or is there any Mac version for this awesome tool?
Thanks!

**Comment by cheat-engine** [comment]
Just a cut down version of 6.2 on the main website. Later I'll continue with porting it to 6.8

**Comment by bournejason** [comment]
Thank you @cheat-engine that'll be really AWESOME!

**Comment by Lutarisco** [comment]
Oh, please, could you let down the "i386" version of Cheat Engine for Mac and port it to 64bit?

I think we really need a good and stable version of CE for Mac.

Thanks.

**Comment by cheat-engine** [comment]
the issue is that lazarus (the GUI library CE makes use of) isn't working 100% yet with cocoa. (right now it only supports carbon, which is apparently 32-bit only)
But CE for MAC should have no issue accessing the uppermemory of 64-bit processes though, it internally makes use of 64-bit address specifiers.

(but yeah, for pointerscans a 64-bit version is probably a requirement, seeing how much RAM it tends to eat)

**Comment by lifeiscontent** [comment]
@cheat-engine any updates on this?

**Comment by cheat-engine** [comment]
it's in the todolist

**Comment by nitrocode** [comment]
Would love to see a milestone and related issues for this to work on.

**Comment by Dougrinch** [comment]
@cheat-engine ?

**Comment by cheat-engine** [comment]
Closing this as there is a decently working CE for mac and mac M1
