### ISSUE TITLE
Track the issues with labels

### ISSUE THREAD

**Issue by wlix32hacker** [cheat-engine/cheat-engine#278]
I'm reading the issues and trying to help fixing them, but I figure that the issues are not flaged with the labels. I think that mark the issues with **bug**, **enhancement** and **helpwanted** labels can help people to easily know what they could work on

**Comment by wlix32hacker** [comment]
This way we can priorize what really is important to be made

**Comment by cheat-engine** [comment]
Unless stated otherwise, you're usually free to fix the issues posted here.
I'm currently busy revamping DBVM(memory management) so don't do too much there, but any other place is fine to edit (Do watch GUI stuff though, don't change font sizes or autosize related stuff, those are horrible to debug)

**Comment by remizovm** [comment]
It'll be great to have at least the "bug" and "feature" labels, imho. Otherwise we can start with just a standard pack.
