### ISSUE TITLE
macOS "Failed opening process. Likely due to lack of admin rights"

### ISSUE THREAD

**Issue by mvaneijgen** [cheat-engine/cheat-engine#2784]
Running Cheat Engine 7.5.2 on macOS 14.2.1 gets you the following result. This is what you get when you try to load any process (Under Privacy & Security I've given the app Full Disk Access and Developer Tools access and set Always attempt to launch as admin in the settings) 

![Screenshot 2023-12-31 at 14 22 08](https://github.com/cheat-engine/cheat-engine/assets/3217544/b7a6fab2-c05e-41b5-9eba-f680c213aa0e)

Was running 7.4.3 before and that had no issues, but I can't seem to find that version anymore. Can I still download the older version?

**Comment by cheat-engine** [comment]
tried launching it using `sudo` ?

**Comment by mvaneijgen** [comment]
I follow this https://www.getce.cn/show/142.html (translated with Google Chrome) and it does not make a difference. Getting the same prompt when trying to select a process (any process)

**Comment by cheat-engine** [comment]
For ios apps and system apps it's expected, but also the same error for the tutorial ?

**Comment by mvaneijgen** [comment]
No the error is different for the tutorial

> The selected process is running under
> Rosetta. To be able to edit programcode
> the debugger needs to be attached.
> Attach the debugger now?

And if I then scan for anything 

> Scan error:controller: No readable
> memory found

But it seems Lies of P https://store.steampowered.com/app/1627720/Lies_of_P/ seems to run a bit different and thus Cheat engine does work. Probably because what you said 

> For ios apps and system apps it's expected

**Comment by cheat-engine** [comment]
Try turning off SIP but some games refuse to launch then

**Comment by mvaneijgen** [comment]
Thanks, I'll check.

**Comment by cheat-engine** [comment]
regarding the "Scan error:controller: No readable
memory found" error, go to settings->scan settings and tick MEM_MAPPED

**Comment by AceHack** [comment]
I'm getting the same error trying to connect to a crossover app

**Comment by ctsstc** [comment]
I've tried to open any process and I'm not having any luck. I've also tried turning on `MEM_MAPPED` but that does not help either. 

I've also tried running it via sudo with hasrights and get the same error. I've tried opening multiple processes without any luck. Is it because the rosetta stone sandboxes it away from the other apps?

**Comment by cheat-engine** [comment]
have you also disabled SIP ?

**Comment by MysticalOS** [comment]
Also getting this, even when I launch the app as root. This seems fairly new to me too, it used to work. Maybe macOS 14.4 tightned security more? last time I used cheat engine I was on 14.3.x

**Comment by cheat-engine** [comment]
Can you run a virtual machine on MacOS that runs an earlier version, or where you can disable SIP seperately from the main system?

**Comment by Muzical84** [comment]
Asking someone to run a Mac VM, given Apple's licensing and etc., is asinine.  Anyway, tried everything here and still no dice.  I did the whole `sudo path/to/ce/ hasrights` thing, set it to try and run as admin on its own anyway, gave it full-disk access as well as input monitoring and accessibility access (trying literally everything I can think of,) and it still doesn't run.  It might be more honest to just pull the macOS version until it's fixed, rather than giving people false hope.

**Comment by cheat-engine** [comment]
So you did disable SIP and that didn't work?  Disabling SIP is a very valid option

**Comment by chinabrant** [comment]
I got the same error. i cant disable SIP, beacuse the game refuse to launch.

**Comment by cheat-engine** [comment]
As far as I know only iOS games tend to refuse tro run when SIP is disabled. If so, then yeah, it's never going to work. (Apple doesn't want you to mess with iOS)

**Comment by theodwya** [comment]
any resolution for this

**Comment by cheat-engine** [comment]
Disable PIP or macos 13 (still won't work on iOS apps)

**Comment by frumplethrall** [comment]
Having the same issue on 752.

I have SIP disabled:

```
csrutil status
System Integrity Protection status: disabled.
```
I ran the following and got this back in the terminal when attempting to run a memory scan - even after it says it successfully attached:

`/Applications % sudo ./CheatEngine752.app/Contents/MacOS/cheatengine-x86_64 hasrights

2024-07-06 03:07:12.214 cheatengine-x86_64[31441:1745543] getMetalPluginClassForService: Failed to find bundle for accelerator bundle named: AGXMetalA12 errno: 0
`

I tried this with Vampire Survivors as a test, since I've had this error in the past and kinda gave up on it. lol.

Is there any information that I could provide that would help in troubleshooting it?

**Comment by qasimraheem** [comment]
just disable sip it will start working, for disabling sip you have to enter recovery mode and then open terminal in recovery mode then use this command `csrutil disable` then restart your mac

**Comment by Prezmi** [comment]
You don't need to disable sip, it works for me.
drag the Cheat engine into apps folder. 
Open terminal
Go to Applications folder
run this:
sudo codesign --force --deep --sign - CheatEngine752.app
It seems to work fine for me

**Comment by MysticalOS** [comment]
That doesn't work and was tried by myself and others per the forum post. It might have worked prior to sequioa but sequioa's security is tighter.

**Comment by Jyxcana** [comment]
I already disabled sip. nothing happens. I still cannot get any access to process.
