### ISSUE TITLE
[AA] define fails on aobscanregion

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#288]
Defining a token fails on aobscanregion, it claims it doesnt know what 'codecave' means.
```
//this fails:
define(codecave,00400019)
aobscanregion(blabla, codecave+50, codecave+100, 00 11 22 33 44)



//this one works:
{
define(codecave,00400019)
codecave:
db 01
}
```

**Comment by mgrinzPlayer** [comment]
aobscan (aobscanmodule and aobscanregion ) are executed before define.

**Comment by FreeER** [comment]
iirc the way CE works is it runs aobscans first, which are implemented to essentially generate define statements, and then the define statements are done later. hence the issue here.

You can work around it fairly easily with lua

```
[ENABLE]
{$lua}
local codecave = 0x00400019
return ('aobscanregion(blabla, %x, %x, 00 11 22 33 44)'):format(codecave+0x50, codecave+0x100)
{$asm}

[DISABLE]
```

Though in that case codecave wouldn't be accessible to other AA code, you'd have to return the entire AA script as a string with codecave replaced with the proper value. But you could also register it as a symbol eg.

```
[ENABLE]
{$lua}
local codecave = 0x00400019
-- register when not editing
if not syntaxcheck then registerSymbol('codecave', codecave) end
{$asm}
aobscanregion(blabla, codecave+50, codecave+100, 00 11 22 33 44)

[DISABLE]
unregisterSymbol(codecave)
```

However you'd probably want to make sure you used unique symbol names for each script... you could probably use the OnActivate event to unregister the symbol immediately after the script was enabled and you likely wouldn't have issues with multiple scripts that way unless a second script could start activating before another finished (theoretically possible with nested scripts or multiple selected, or via lua...) eg.

```
[ENABLE]
{$lua}
local codecave = 0x00400290
-- register when not editing, do not save symbol in table (won't register if already exists)
if not syntaxcheck then registerSymbol('codecave', codecave, true) end
-- memrec exists in CE 6.7+ (not sure when syntaxcheck was added to be honest...)
local memrec = memrec or getAddressList().getMemoryRecordByDescription('the name of this memory record')
memrec.OnActivate = function(memrec, beforeEnabled, enabledNow)
  if enabledNow and not beforeEnabled then unregisterSymbol('codecave') end
  return true -- allow it to finish activating
end
{$asm}
aobscanregion(blabla, codecave+50, codecave+100, 00 11 22 33 44)

[DISABLE]
```

It's a little cleaner without comments or support for older versions of course. Of course 90% of that could probably go in a function in the table's lua script and you could just call it with luacall in each script, though if you're using symbols with static addresses you don't really need lua, you can manually define them (memory viewer->Tools->user defined symbols) and they'll be saved with the table (but they really would need to be unique to each script in that case).

**Comment by Symbai** [comment]
Ok but cant you just check for define statements first then or is there a technically reason why it is like it is right now?

**Comment by mgrinzPlayer** [comment]
Use this Lua script in autorun folder. It will move all define interpretation to Lua engine due to AutoAssemblerPrologue functionality. DarkByte provided this function so we can change few things...

```Lua
local function trim(s) return s:match'^()%s*$' and '' or s:match'^%s*(.*%S)' end

local function tokenize(s)
  local tokens = {}
  local a,b = s:find('[%w_#@%.]+')
  while a do
    tokens[1+#tokens]={token=s:sub(a,b),position=a}
    a,b = s:find('[%w_#@%.]+',b+1)
  end
  return tokens
end

local function replaceToken(input,token,replacement)
  local tokens=tokenize(input)
  local result=input
  for i=#tokens,1,-1 do
    if tokens[i].token==token then
      local pos=tokens[i].position
      result=result:sub(1,pos-1)..replacement..result:sub(pos+#token)
    end
  end
  return result
end

local function forceDefineBeforeAOBSCAN(script, syntaxcheck)
  local defines = {}

  for i=0,script.Count-1 do
    local line = trim(script[i])
    local parameters = line:lower():match('^define%(.*%)$') and line:match('%((.*)%)')
    if parameters then
      local args = {}
      parameters:gsub("([^,]+)",function(c) args[#args+1] = c end)
      if #args>1 then
        defines[1+#defines] = {name=trim(args[1]), whatever=args[2]}
        script[i]=''
      end
    end
    for _,define in ipairs(defines) do
      for i=0,script.Count-1 do
        script[i] = replaceToken(script[i],define.name,define.whatever)
      end
    end
  end
end

if forceDefineBeforeAOBSCAN_ID~=nil then
  unregisterAutoAssemblerPrologue(forceDefineBeforeAOBSCAN_ID)
  forceDefineBeforeAOBSCAN_ID=nil
end
forceDefineBeforeAOBSCAN_ID = registerAutoAssemblerPrologue(forceDefineBeforeAOBSCAN,false)```

**Comment by Symbai** [comment]
Nice one! Then I dont have to create the lua code every time myself for my own scripts but when sharing tables I use FreeER's solution. Thanks everyone!
