### ISSUE TITLE
feature: LUA Inspector

### ISSUE THREAD

**Issue by JasonGoemaat** [cheat-engine/cheat-engine#308]
It would be nice to have a LUA object inspector.  I imagine calling it like this:

```
inspect(getMemoryViewForm())
inspect(myLuaTable)
```

It would be in a tree sorted by so you could drill down.  For userdata objects it could use `getmetatable()`, and merge that for normal tables, something like the output of this:

```
local mf = getMemoryViewForm()
local mt = getmetatable(mf)
local keys = {}
for k,v in pairs(mt) do table.insert(keys, k) end
table.sort(keys)
for i,k in ipairs(keys) do print(tostring(k).." = "..tostring(mf[k])) end
```

It would use the ClassName and Name properties if available for the string value (i.e. `TMemoryBrowser MemoryBrowser`), and handle controls, probably using a table generated using `Control[]` and `ControlCount` for example, same for components and menus...

**Comment by FreeER** [comment]
So wrap that in a function, put it in a lua file and share on the forum for people to put in CE's autorun folder?

If everyone loves it and asks DB why it's not in CE then perhaps it'll make it's way there like pistons did in Minecraft...

**Comment by JasonGoemaat** [comment]
I was planning on working on it myself, I just created the issue to keep track of it and get any comments...

**Comment by FreeER** [comment]
Fair enough, it's not always obvious :)
It's not particularly uncommon for people to use issues to ask questions or generally complain, and it's also something pretty small that could have been done as a PR with some suggested code rather than a fairly open ended comment.

Anyways, as for comments, all I can say is I can't remember personally wanting this but can kind of see some liking it. I think I've looped through a metatable to find functions once, generally I just look at the classname (if I don't already know what it should be) and then look at the documentation in celua.txt in my text editor where I can do arbitrary searches, or if I can't find it there hop over to the source (and then try to document it in celua.txt for the next release).

**Comment by cheat-engine** [comment]
I think the code completion is similar to this.
