### ISSUE TITLE
IGT Kitty Glitter Slots by BigFish Games "Found 0" message in Cheat Engine

### ISSUE THREAD

**Issue by Moltresrider** [cheat-engine/cheat-engine#321]
When searching your coin value in this game, it always says "Found: 0" despite the fact that the exact amount is definitely in memory.

If your coin value is a common number and you click 'next search' when your value changes, same thing, now it says "Found 0"

The fact that the value is definitely there and is displayed on screen in the game but Cheat Engine cannot find it means that the problem is in Cheat Engine's side.

**Comment by FreeER** [comment]
"The fact that the value is definitely there and is displayed on screen in the game but Cheat Engine cannot find it means " literally nothing.

I can come up with 3 different options off the top of my head for why that can happen.
1. It's not stored as the type you're searching for, try "All", but it doesn't even have to be stored as one of the types CE supports by default.
2. It's not stored as little endian which is how CE scans for values, on Windows this is most common with emulators.
3. various versions of anti-cheat.
actually I can come up with a 4th, you're attached to the wrong process. This is especially common with chrome/gamemaker games which have multiple processes even when they have only one visible application window.

There's probably a couple more I'm not thinking of. If you're a programmer think of CE as the compiler, the compiler is never wrong (except in the extremely rare cases that it is). If you're not a programmer think of CE as your girlfriend/wife, shut up and do what they need you to do to make them happy, ie. they are never wrong (except for the extremely rare cases where they are, ie. drunk etc.).

**Comment by dsasmblr** [comment]
In addition to what Ben said:

1. The game might be switching memory addresses each time the value
changes, which would make your "next" scans ineffective. This isn't common,
but a possibility.
2. The value displayed on the screen isn't the actual value in memory.
Maybe it's a string. Maybe the number is built in some odd way, like if
it's 96 on the screen, then it's storing the 10s value in one memory
address and the 1s digit in another.

Suffice it to say, the problem is likely the way the game handles that
value and your current scope of knowledge.

**Comment by Moltresrider** [comment]
That cannot be it, because Cheat Engine does the SAME thing for older games like Ant War from 2007 and Final Fantasy VII from the late 90s/early 2000s.

same "0 found" and I am pretty sure it SHOULD work on Final Fantasy VII

**Comment by FreeER** [comment]
Well first, yes, it can be. Just because it has the same result elsewhere doesn't mean any of those options are suddenly impossible any more. Just because you get the same result doesn't mean they can't have different causes. If that doesn't make sense then here's a basic example, you can't say it's impossible for your car to be out of gas because some other car you had that wouldn't start had a dead battery. Same result, different causes.

If you get the same error for other games where you know for a _fact_ that it should work because you've found a working table for your version of the game that has addresses/scripts for the value and it's definitely stored as a standard 4 byte little endian value matching the displayed value, _then_ you can say it's almost certainly something else, but only _almost_ because until you actually fix the problem and recheck it could _still_ be one of the above (ie. you can have a dead battery _and_ be out of gas)

So... have you actually checked whether those other games are using the type you're searching for with the same value displayed? If so, are you running as administrator? If so, perhaps try resetting CE (there's a ceregreset.exe in the installation folder) or reinstalling it.

**Comment by dsasmblr** [comment]
You mean the Ant War that might have some sort of anti-cheat implementation
built in, or is perhaps running in some sort of emulated environment, etc.?
http://purecheatingforums.forumotion.com/t201-ant-wars

Note the third post down--specifically this: "The variables all randomize
every 10 secs..."

That would explain why your simple memory scans aren't working.

As for Final Fantasy VII, are you playing it in an emulator like ePSXe?
Because if so, then the 2nd point in Ben's initial reply to you is
applicable--meaning that, again, your basic value scanning isn't going to
return the results you expect.

And in regards to the original game you mentioned, which version are you
playing? In-browser? If so, then you may be playing a server-based version,
which means your values are likely moving around in different memory
addresses when they change.

You've almost miraculously chosen games that perfectly exemplify where
basic memory scanning fails, lol.

Trust us when we say/imply that the issue here is your current lack of
knowledge, not Cheat Engine.

**Comment by Moltresrider** [comment]
first off, I SAID "ANT WAR" NOT "ANT WAR**S**" THEY ARE TWO DIFFERENT GAMES!!!

as for Final Fantasy VII, it is the PC and it is old. It should work because it was made before Cheat Engine was made so it should NOT have ANY blocks against it

**Comment by dsasmblr** [comment]
Well, you also said 2007 (which that forum post is dated), but that's
incorrect if the 2003 game is what you're talking about (
https://en.wikipedia.org/wiki/Ant_War).

Specific links to these games and more clarity as to versions would
drastically help reduce misunderstandings. Just FYI for your future
inquiries.

As for Final Fantasy VII, here are 2 threads on FRF containing cheat tables
for the PC version of the game:

http://fearlessrevolution.com/viewtopic.php?t=4713
http://fearlessrevolution.com/viewtopic.php?t=1205

Again, Cheat Engine isn't the problem; however, your fundamental
misunderstanding of how CE works, as well as y our lack of wanting to
understand and/or attempt what we're trying to tell you, is. And that's
good news, because it solves the mystery of your issues.

Now, you can either do something proactive and attempt to educate yourself,
or you can keep saying the same thing 20 different ways in hopes that
you're going to magically be right one of those times.

**Comment by Moltresrider** [comment]
Idiot cannot link me to the correct version! I SAID the version from early 2000's NOT THE STEAM VERSION WHICH IS CONSIDERABLY NEWER!!!! READ WHAT I FUCKING TYPE!!!!!!!!!!!!!!!

and the Ant War is from Reflexive Arcade which no longer exists so I do not have a link.

**Comment by dsasmblr** [comment]
Top troll, my man. gg.
