### ISSUE TITLE
Debug breaks MonoDataCollector

### ISSUE THREAD

**Issue by JasonGoemaat** [cheat-engine/cheat-engine#332]
When I've enabled 'Activate mono features' and a breakpoint is hit like when 'Find out what accesses this address', both CE and the game freeze for several seconds and mono features are deactivated.  If the MemoryViewer window is open, a lua window pops up showing the error:

    Error: monoscript.lua:408: attempt to index a nil value (global 'monopipe')

I'm guessing that since the mono data collector is loaded into the game process that it doesn't like being debugged and is causing the crash.   Would it be possible to do any of the following?

1. Just let MonoDataCollector keep going and resume after a debug breakpoint has passed
2. Allow deactivating mono features by clicking the option again so it can gracefully be stopped before setting a breakpoint and restarted after you're done watching for changes?
3. Change the mono code in CE to detect if a breakpoint has been hit and just not call lua?  I don't think this is viable because the breakpoint could be hit after the check

The second option can be done just by adding the first condition here:

```lua
function miMonoActivateClick(sender)
  if monopipe ~= nil then
    monopipe.destroy()
    monopipe=nil
    return
  end
  if LaunchMonoDataCollector()==0 then
    showMessage(translate("Failure to launch"))
  end
end
```

**Comment by cheat-engine** [comment]
It does that because you're asking the game to give you the name for an address you're looking at, but the game is not responding, because it's frozen. In that case CE does a graceful disconnect from the game

what you can do is in `monopipe.OnTimeout=function(self)` start a timer that checks if the target is paused, and if not reattach 

You can use debug_isBroken(),  but you also have to check the pause button, and that the target hasn't actually been suspended by the resource monitor program in windows.  (Which is why I didn't do that as it's just a too big hassle)

2: You can set the timeout to something like 100 so you don't even notice it's disabling it automatically

3: Yup, the reason why 6.6 would occasionally freeze solid was because a breakpoint would hit right after the check if a breakpoint could get hit
