### ISSUE TITLE
Second scan returns "0" even though there ARE values matching that scan changed from the original scan

### ISSUE THREAD

**Issue by Moltresrider** [cheat-engine/cheat-engine#356]
I searched 1000 in Cheat Engine using the "All" method, I bet $100 in Vegas Stakes for Super Nintendo using the ZSNES.exe process. I had 900 remaining.

I saw in the list of values, three "900" values. However, when I do my second scan for the value 900. It says that there are 0 values when the side said that there was at least THREE values that were 900 from the original list of values from the 1000 search.

Even though there WERE values that changed from 1000 to 900 and they were listed in the side, Cheat Engine still thinks that there are no values that went from 1000 to 900. Again as soon as I bet 100, three values went from 1000 to 900 according to the list on the side, but when I do my second search of 900. It returns no results.

**Comment by cheat-engine** [comment]
ZSNES emulates a big endian system, and I suspect it also keeps it in that format
So, try the 2 byte big endian type at https://forum.cheatengine.org/viewtopic.php?p=5305367#5305367
Or wait till the value is below 256 and use 1 byte scans  (OR use 1 byte scans to begin with. The values won't show the right value, but the address will be correct)

**Comment by Moltresrider** [comment]
That DID NOT work for me!! I tried it on three games all with the SAME results. It found about 40 values with that number, however there are 0 for the second scan. In fact, there were no values that changed when the value in the game changed. I had 300 GP in Final Fantasy II (IV) I spent 30 GP and had 270 GP left. There were no 270 values and no results on second search

**Comment by dsasmblr** [comment]
If you're insistent upon using ZSNES, you should just use its native cheat
creation tool. You can do exact value scans and comparative scans with it
to easily find values; however, exact values won't always be the right
values.

I looked into the game you mentioned, using ZSNES, and found that your
problem is as follows:

*1*. You didn't select to scan both read and write memory (it's a checkbox
towards the bottom of the "Memory Scan Options" box that says "Writeable",
of which you can hover over to see what the options are if you click that
box). CE defaults to scanning writable memory. All the addresses I found
related to money reside in static addresses (they're the green ones, which
is actually good for you because it means you can find those addresses once
and you're all set...so long as you're able to directly modify the values).

*2*. There are a lot of values related to money in that game, but none of
them that I futzed with seemed to change the actual value, which leads me
to believe there are more values to find or you're going to have to rely on
a code injection to write your own value that way. There is one value which
represents the exact value you see on the screen; however, it's a display
value only, which means you might see the value change on the screen, but
your real money value stays the same. Such is the case with the ~5 values I
found seemingly related to money.

*3*. The instructions that read from/write to the address of player money,
also do a ton of other things in the emulator, so...shared instructions
which you'd have to find a way to single-out money to write a custom value
(if it would even work).

*4*. Each digit has its own byte representation for values:

0x16 = 0
0x17 = 1
0x18 = 2
0x19 = 3
0x1A = 4
0x1B = 5
0x1C = 6
//--Here it skips to 0x26 for reasons which I haven't tried to figure out
yet.
0x26 = 7
0x27 = 8
0x28 = 9
0x29 = the yellowish character you see flashing when you choose to raise
your bid

*5*. There is a byte of C3 between every byte representing the digits I
noted above (meaning exact value scans for anything but single-digit 1-byte
value, will fail). So, for example, if your money is 000001337, then a new,
read-memory AOB scan for hex value C3 16  C3 16  C3 16  C3 16  C3 16  C3 17
C3 19 C3 19 C3 26 would return your value (of which you might see multiple
of, so you'd have to change your money value somehow, then do a next scan
for that new exact value).

I'm not sure how ZSNES is programmed, because it doesn't seem to strictly
follow a bittedness in a way that a common custom value (like 4-byte Big
Endian) solves (*does that byte array/legend look familiar to you at all,
DarkByte?*).

So, if you're up for a challenge, then use my notes above to try to conjure
up your own solution.

*The key takeaway for you is that all of this is NOT the result of a bug in
Cheat Engine.*

Ideas for you:

- Find the value related to bidding and make it such that you actually bid
0, effectively keeping your actual money the same value until you win money.
- Take my notes above and use them to figure out what you need to do to
alter player money.
- Use ZSNES's inbuilt cheat tool (should be plenty of tutorials around to
teach you how to do that) and see how you fair.
- Use a different SNES emulator, like a RetroArch SNES core, or SNES9x, etc.

**Comment by bawgrobin** [comment]
https://github.com/cheat-engine/cheat-engine/issues/408

go to settings and set the values you want CE to search for when selecting _all_
