### ISSUE TITLE
Cheat Engine 6.8 BUG

### ISSUE THREAD

**Issue by cnllj** [cheat-engine/cheat-engine#368]
![default](https://user-images.githubusercontent.com/37143379/41715489-36007dac-7586-11e8-8544-7a699873d055.png)
When debugging, the mouse moves to the main window

**Comment by cheat-engine** [comment]
Do you have lua timers running ? (asking because of unnamed timers)
Does this happen every time ?

try (overwrite the files in this zip with the one in your CE binary folder with ) http://cheatengine.org/download/ce-6815595.zip
and see if it still happens.  If it does, hold down ctrl, click help, and then check "Generate errorlogs"
Next time an access violation occurs (preferable not just a timer exception) it should generate a cedebug.log file which I can use to track down the cause

**Comment by cnllj** [comment]
Thank you, these files have solved this problem. The problem version is 6.8.0.6
