### ISSUE TITLE
How can I show the dbvm's log?

### ISSUE THREAD

**Issue by hsac1313** [cheat-engine/cheat-engine#479]
Like this...

sendstringf("~~~")

**Comment by cheat-engine** [comment]
compile dbvm in debug mode.
in the makefile setup the io port of your serial (can be an pci/pci-express port, but you'll have to find out the port them, preferable set it to dos compatible)

Then attach another computer to your system using a nulmodem serial cable and start a terminal program on the other system (putty works)

If you're launching DBVM from inside a running windows environment instead of booting, then before launching DBVM open a terminal on the host as well and establish a connection.  (type something on both ends to confirm it's working)

with debugmode on dbvm will exit on a bunch of events and then ask what you wish to do.  vmmhelper has a switch/case system that lets you decide if you wish to skip certain events, and there's also a debug level in place 

--

Also, if you have a system with jtag capabilities (gigabyte mainboards with usb3 of 2-3 years ago tend to have a good chance to work) then you can try intel system studio Ultimate (and a usb-A<->usb-a cable)
In the system debugger you can make it load vmm.elf which will then show the sourcecode at the appropriate location  (just set the base as 0) and lets you step through certain parts of the code

**Comment by hsac1313** [comment]
Thanks to you.
I'll close the issue.
