### ISSUE TITLE
metin2 

### ISSUE THREAD

**Issue by 60rap60** [cheat-engine/cheat-engine#484]
cheat enginiede speed hack kullandığımız zaman oyun hızı artıryor ve oyun hızı artıncada oyundan atıyor benim istediğim oyun hızı arttırmak yerine oyundaki karekterin hareket hızını arttırmak neden hız hilesi kullanmıyosun derseniz eğer hız sınırı var hile açınca atıyor cheat engine açınca kısıtlı bi zaman boyunca atmıyor işin kısası bu konuda yardım edebilecek varmı

**Comment by korcankaraokcu** [comment]
Karakterinin hızı server sided olabilir, CE ile sadece client sided verileri hackleyebilirsin. Ayrıca forumda da belirtildiği gibi Cheat Engine online oyunları desteklemez, bunlarla ilgili açacağın issuelara cevap alamazsın. Zaten ingilizce yazmazsan hayatta cevap alamazsın, derdini anlatacak kadar öğren ve başlıklarını "x oyununu nasıl hacklerim" değil de belli teknik kısımlarda yaşadığın sorunları nasıl aşabileceğinle ile ilgili aç

@cheat-engine This issue is asking for an assistance to hack an MMORPG called Metin2, it's basically useless, you can close it
