### ISSUE TITLE
Randomize window title string

### ISSUE THREAD

**Issue by Muffindrake** [cheat-engine/cheat-engine#491]
Some anti-cheating measures famously scan process lists for window titles and specifically look for the string "cheat engine" and then trigger, even if cheat engine isn't remotely used to do harm to that program

https://old.reddit.com/r/leagueoflegends/comments/aayvu4/lol_reads_your_browser_tabs_is_this_a_gross/

Which is funny and stupid, because there are far better debuggers that can do what cheat-engine does - and more.

Randomizing the window title would force those developers to stop using their brain-dead, generously-named 'heuristics' and deploy more sophisticated measures like actually checking whether the program is trying to read memory. Or the next-closest thing, checking whether cheat engine is installed.

**Comment by Symbai** [comment]
1. Its open source, you can download, change it and compile yourself
2. https://www.murgee.com/window-title-changer/ (or similar) if you for any reason cannot compile it yourself
3. Checking for window title is one of the worst anticheats exist. There are plenty of ways it still can be detect by file signatures or drivers loaded, compare icons, installation paths, process names, button arrangement on window, etc. Also it won't help against heuristics because the heuristic just gets wider. If devs cannot detect it one way they try another. In worst case we will have the same effect as AVs nowaday which flags 100% identical code 100% differently for no reason.

**Comment by cheat-engine** [comment]
MainForn.Caption='whatever'
getApplication().Title='something'
