### ISSUE TITLE
Request - shared Dropdown Selection options

### ISSUE THREAD

**Issue by BitwiseX** [cheat-engine/cheat-engine#501]
I'm having some problems with table sizes because of this. You get something like an RPG with lots of long lists of IDs in a struct and you quickly get into exponential file size growth. 

I'll use Disgaea 5 as a particularly pathological example; there's a list of item stat boosters in the game called innocents which are stored as an ID and an int for the amount of boost. You can innocents in a special warehouse (256 entries) or they can be attached to items (8 per item). Every character (of which there are 128) has 5 item slots and you can have 2000 items in your inventory. So if all of those were editable the dropdown selection options would be in the .ct file 21376 times (256 + (8 * 2000) + (8 * 128 * 5)). That's just the worst example in that game, there are many more. 

If this isn't possible/too much work, would having compressed .ct files be possible instead? I'd imagine that'd any compression algorithm with a dictionary would have huge wins for file size just by virtue of how repetitive/verbose XML is.

P.S: I know there's a Lua plugin called Dropdown List Editor to help with this - I use it myself for editing tables - but it just swaps the exponential file size growth for exponential load time.

**Comment by BitwiseX** [comment]
I did not try that - I didn't know it was a thing. Google and duck duck go were less than helpful.

Is there any kind of tutorial on this? I've just been using Value:Description 'till now; I have no idea what memrecdescription refers to and googling it just points me to the frmmemoryrecorddropdownsettingsunit.lfm in this repository. :disappointed: 

Just for my benefit as well, what version of Cheat Engine was this introduced/vaguely working?

**Comment by mgrinzPlayer** [comment]
"address list entry" aka "memory record" has description.

![obraz](https://user-images.githubusercontent.com/9157726/51367277-0fb99200-1aea-11e9-8a2c-8bf7c1903a69.png)


if you use (memrecdescription) it will find the first memory record with that description, if you have few or more memory records with the same description, only the first one will be used.

Here is the example and file
![obraz](https://user-images.githubusercontent.com/9157726/51367700-22cd6180-1aec-11e9-802d-f3b382c99acb.png)
[example.zip](https://github.com/cheat-engine/cheat-engine/files/2771727/example.zip)

memory record "slot1" for character1 has "normal" Value:Description pairs.

slot**2** - slot**4** for character**1** and slot**1** - slot**4** for character**2** are using built-in feature (there is (slot1) instead of value:description pairs).

**Comment by BitwiseX** [comment]
Man that works perfectly. It was exactly what I was looking for; thankyou very much! :grin:
