### ISSUE TITLE
EFI version of DBVM

### ISSUE THREAD

**Issue by buraktamturk** [cheat-engine/cheat-engine#521]
Hello,

Is there any compiled version of EFI DBVM loader? Or is there any instructuons about how can I compile it? Does it support loading Windows after it is loaded by EFI?

Thank you,

**Comment by cheat-engine** [comment]
It's been a while that i worked on it and will likely need some fixes to work with the new LoadedOS struct 
But basically you just need a bootloader that can load the dbvm.efi and afterwards launch the windows efi
i used to use the open source efi loader 'rEFInd' to do that

**Comment by buraktamturk** [comment]
Thank you so much for your response.

I am volunteer to update the loadedos struct. Can you point out where to find dbvm.efi (if it is compiled somewhere)? And how to compile it? (the tooling: gnu make? cmake? gcc? visual studio?)

Thank you,

**Comment by cheat-engine** [comment]
I found an old DBVMUEFI.EFI file in my worksystem from end 2017 (so that should say how old it is)
[DBVMUEFI.zip](https://github.com/cheat-engine/cheat-engine/files/2845477/DBVMUEFI.zip)

It will need a version of vmdisk.img in the rootpath or efi path (not sure which one, best do both lol)

As for compiling, I use eclipse with the CDT package(for C/C++ support), and have added the EFI header files (gnu-efi package perhaps? But I could be wrong)

**Comment by cheat-engine** [comment]
Just updating that the current github project will work with the latest DBVM

**Comment by cheat-engine** [comment]
Here's the contents of my EFI bootdisk
[dbvmefi.zip](https://github.com/cheat-engine/cheat-engine/files/3331995/dbvmefi.zip)

**Comment by buraktamturk** [comment]
Thanks! I am closing the issue as anyone interested on the file can access it via GitHub issues search.
