### ISSUE TITLE
no file   {$I frmsymboleventtakinglongunit.lrs}

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#528]
frmsymboleventtakinglongunit.pas(61,4) Fatal: Cannot open include file "frmsymboleventtakinglongunit.lrs"

initialization
  {$I frmsymboleventtakinglongunit.lrs}

end. 

  {$I frmsymboleventtakinglongunit.lrs} -> error no compile

**Comment by kitty8904** [comment]
And you can not upload the latest VMDISK.IMG file to the GIT Upload Possible?

I can not compile Linux DBVM

**Comment by kitty8904** [comment]
The subtle speed difference of VMDISK.IMG? I do not know exactly

Dragging does not slow down the window

Blue screen still happens when debugging I do not know why

//{$I frmsymboleventtakinglongunit.lrs

The lrs file is missing and commented out and tested

6.8.3 test

**Comment by cheat-engine** [comment]
I don't know why your system BSOD's either. 
My test system with only 4 Cores with hyperthreading seems ok, so it could be the total number of cores.  Perhaps you can disable some in the bios before booting and see if it has an effect?

Also, have you tried debugging just the tutorial ? (Just to see if it's the debugger or the target that does something sneaky to crash dbvm)

**Comment by kitty8904** [comment]
<img width="257" alt="6" src="https://user-images.githubusercontent.com/18622105/52771770-249e2c80-307a-11e9-8d65-9092ebfa2372.png">

What does the returned number mean?

Less cores do not cause blue screen(hyperthread off)

Multi-core problem? If I can not resolve it, I think I should finally go back to Windows 7

//////////

Is there a way to know the speed difference?

I do not know if there is a difference
(DBVM 12 VPID)

**Comment by cheat-engine** [comment]
The numbers return number of times a specific VMEXIT happened (e.g 10 is the number of times CPUID has been called)
Local is for the current CPU, Global is for all CPU's combined


The 2nd one is the total count of all CPU's


As for the crash:
It's possible that the driver just causes a crash because it doesn't take into account taskswitches while inside the interrupt handler and the return would then cause an invalid stack, which in turn would have caused a spontaneous reboot, and because it's in DBVM it would just exit the VM and freeze.
And with more cpu cores the chance of that happening might be higher. (But can of course be something else as well. I just haven't been able to reproduce it)


///
You can do a benchmark with the old vmdisk and the new one and see if there's a visible change.
Some people complained that their games would only run at half speed with DBVM before (though on my test system I didn't really notice)

**Comment by kitty8904** [comment]
This time my head was sick with the DBVM blue screen, but I could not figure out why other than multi-core.

/////////////

I see the DBVM speed difference when I see it with my eyes

I wondered how fast it was

I have solved the WPM RPM that had a problem in the past. I appreciate the continuous update of the Cheat Engine without interruption
