### ISSUE TITLE
Will DBVM debug options be added?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#548]
<img width="713" alt="vv" src="https://user-images.githubusercontent.com/18622105/53342153-b4808800-3950-11e9-83c6-5dd794d4ec83.png">

1.DBVM Change Register at this lucation

2.F5~F8 BreakPoint Trace DBVM?

3.BreakPoint DBVM GUI List view and delete
(DBVM BreakPoint no view)

Thanks for adding more DBVM features

**Comment by cheat-engine** [comment]
1 i can easily link the existing one to the gui
2 this will either require a full display driver for dbvm that can save and restore the current display, or a changeregonbp where rip changes to a veh type debug handler. But since there might be a reason you're not using VEH debug with page exception bp's I don't think it's such a good solution. (using lua's loadModule to manual map the vehdebug and then use the veh debugger won't work?)

3 it's not 'really' a breakpoint, and the debuggerthread isn't even running so there is no bplist, but i'll look into it

**Comment by kitty8904** [comment]
I still can not solve DBVM blue screen problem (global debug breakpoint, no ept breakpoint)

I still do not understand the problem of Watchdog Blue Screen, 

so I am happy to add DBVM debugging feature
