### ISSUE TITLE
"dbvm_cloak_activate" alloc too much memory

### ISSUE THREAD

**Issue by pyj2323** [cheat-engine/cheat-engine#579]
When I cloaked 1 page with 8 cpu cores, 8+1 pages  were allocated from very small pool(total 700 page).
When I cloaked 1 page with 36 cpu cores, 36+1 pages (oh my god) were allocated and my computer stopped when out of memory(after about 10+ pages cloaked). 

So I have some questions.
1. Why does dbvm allocate as many as cpu core count? I think 2 pages(execute page, data page) is enough for 1 page memory cloak. 
2. Why is memory pool so small although my computer ram is 192GB? 
3. Why don't dbvm use outer physical memory(very big) to redirect cloaked page instead of use very small memory?

![1](https://user-images.githubusercontent.com/32794121/54450869-c8bbe600-4794-11e9-9178-d02c72b2f769.jpg)
![2](https://user-images.githubusercontent.com/32794121/54450873-cb1e4000-4794-11e9-9b43-f8a333c6f142.jpg)
![2 - 복사본](https://user-images.githubusercontent.com/32794121/54450875-cc4f6d00-4794-11e9-806a-adad041db909.jpg)

**Comment by cheat-engine** [comment]
I didn't expect you'd want to do 10+ regions.  I recommend also changing the list to a map instead of an array then (though DBVM doesn't have a map implementation yet so that needs to be added first) as it may start slowing down after that

Anyhow, you can add more RAM by calling vmx_add_memory with a list of physical pages that you know won't be used by the system anymore (e.g allocated by your driver)
or go to vmxoffload.c and change vmxoffload_override so instead of 64KB per processor it allocates more

**Comment by pyj2323** [comment]
Tens of pages(or hundreds) need to be cloaked when I want to hide full .text section from memory scanner.

thanks. Is there answer to question 1?

**Comment by pyj2323** [comment]
thanks for answer

Hundreds of pages need to be cloaked when I want to hide full .text section from memory scanner.

**Comment by pyj2323** [comment]
anticheats are so good at kernel monitoring so I load dbvm and unload kerneldriver and use usemode programs which do vmcall. dbvm is getting important at game cheating.

**Comment by cheat-engine** [comment]
you can now use dbvm_addMemory(pagecount) to add as much RAM as you like

(also cloaked regions don't degrade speed after 20 anymore)
