### ISSUE TITLE
luaDebug on ceserver

### ISSUE THREAD

**Issue by KenjiroIchise** [cheat-engine/cheat-engine#645]
I would like to use luadebug on ceserver.
The behavior of debug_setBreakpoint, debug_removeBreakpoint, debug continueFromBreakpoint is unstable.
There is no problem if the above is done using Toggle breakpoint on the disassembly screen. 
What is the difference between debugging on lua and debugging on the disassemble screen?
 I think lubdebug is very powerful if it is available on ceserver.

**Comment by cheat-engine** [comment]
lua_setbreakpoint (when execute bp)
https://github.com/cheat-engine/cheat-engine/blob/f3135fbda1ed53936f310ac2a6524176313abd55/Cheat%20Engine/debughelper.pas#L2002

togglebreakpoint:
https://github.com/cheat-engine/cheat-engine/blob/f3135fbda1ed53936f310ac2a6524176313abd55/Cheat%20Engine/debughelper.pas#L2176

They all end up calling addbreakpoint so it depends on the parameters passed (with lua you have more options)

What is the lua code you try, and describe how it is unstable

Also, toggle breakpoint happens when you as user manually press it, usually during a time when not much happens in the game, so if there is an issue with speed, you won't get affected by it.  But if you automate setBreakpoint it's likely it happens during an active state of the target, where many things can go wrong

**Comment by KenjiroIchise** [comment]
I decided to write code to hook clock_gettime using luaDebug. There was no problem if I set breakpoints manually using toggle breakpoints, but doing so with lua could cause crashes. However, luaDebug worked fine for operations that are not run frequently. I think this can be a very powerful dynamic debugging tool.
