### ISSUE TITLE
help is cheat engine malware

### ISSUE THREAD

**Issue by someboithatscalledalloy** [cheat-engine/cheat-engine#677]
so my antivirus which is avast (its free) thinks or sees that cheat engine has malware or a virus is this true cause i really want cheat engine and i lost my progress in a game and i want to cheat now cause im really mad and want it back but i want more now so i want to cheat it in so

is cheat engine a virus or has malware i really want to know
thanks

**Comment by cheat-engine** [comment]
go read through the sourcecode and see if you can find the virus

also, a PUP is not a virus

**Comment by someboithatscalledalloy** [comment]
well i retryed and avast says that it got rid of cheat engine cause it had malware so its not a virus but is it really malware

sorry i thought it was a virus

**Comment by Raijinili** [comment]
Cheat Engine is nefarious. It hacks into your other programs. But you know that it is nefarious. That's why you got it in the first place.

PUP means "Potentially Unwanted Program". It's a way for your antivirus to say, "Hey, did you install this on purpose? If not, then it snuck onto your computer and you should probably get rid of it." PUP should be ignored for software you installed on purpose.

I'm really just commenting to remind someone to close this issue, as it's not really an issue.
