### ISSUE TITLE
doesn't open

### ISSUE THREAD

**Issue by KOUBASGR** [cheat-engine/cheat-engine#771]
i download the cheatengine683 i delete the badlion i reboot my pc i disable my antivirus and still doesnt open pls help

**Comment by cheat-engine** [comment]
Reboot your system using start->power->restart (NOT shutdown)

Also, you say 'delete' the badlion, but do you mean uninstall with that or do you mean you just deleted the files you think are part of it? Because it also has an uninstaller that you have to use to get rid of that malware

alternatively, try this code in an command prompt running as administrator
```
net stop BadlionAntic 
net stop BadlionAnticheat 
sc delete BadlionAntic 
sc delete BadlionAnticheat 
```
