### ISSUE TITLE
Request: Dissect structure fill with X

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#803]
Would be great having an option to add Y entries with X data type. For example I want the first 300 bytes to be data type of BYTE. As of now I have to

- Delete the existing entries
- Add one byte entry
- Add another byte entry
- Repeat until i'm at 0x300

It would be much easier if I could have an option in the add element window that lets me define the amount of elements to add.

**Comment by cheat-engine** [comment]
create a one byte entry
select it
ptess ctrl+c
hold ctrl+v till you have as many as you like

Also, instead of using structure dissect for byte comparisons you can use hexview for that
Just open a second memory viewer window, then go to the other object in hexview, rightclick and choose show differences
