### ISSUE TITLE
Segurazo? Stop with this malware!

### ISSUE THREAD

**Issue by Melvasul** [cheat-engine/cheat-engine#816]
Do you really think it is a good practice to add malware into your installer and making it's "no installation" being practically hidden into your installer!

First photo showing how it's absolutely anti user the way you will or won't install it(and it is a malware, why are you going to install a malware?)
![CE](https://user-images.githubusercontent.com/11297488/62533441-fd653280-b846-11e9-8dd2-3a9d8fafcc02.PNG)

even if they are going to be installed THERE'S NO WAY FOR THE USER TO REALLY KNOW IT OR NOT because the main installer won't tell you!
![CE2](https://user-images.githubusercontent.com/11297488/62533447-00602300-b847-11e9-979d-51843096e679.PNG)

**Comment by cheat-engine** [comment]
click on "Cliccq gui" to opt out

**Comment by Melvasul** [comment]
Look at the second image which is the step next to that one.
The installer won't tell you if that crap will be installed or not.

**Comment by TheNekOz** [comment]
> click on "Clicca gui" to opt out

Ok, how the frick are we supposed to know that? I don't speak whatever that language is.

**Comment by AniLeo** [comment]
That's no excuse for you to bundle malware with your installer
https://blog.malwarebytes.com/detections/pup-optional-segurazo/

Have some respect for your users, if you're going to bundle adware at least bundle inoffensive stuff

**Comment by Hanif1601** [comment]
**Please stop spreading malware on your installer, dev**. This is really important for average users or consumer.

**Comment by cheat-engine** [comment]
I don't control which advertisers are being shown to you. Go to ironsource( https://www.ironsrc.com/ ) about any concerns you have regarding the companies they do business with. (it's similar to google adsense but then for applications)

as long as you can opt-out i have no problem with it.

**Comment by FransBouma** [comment]
My mod releases here on Github got flagged for containing 'easyinjector' which was 'malware' according to github. This crap in the installer is 10 times worse. It's a matter of time before someone reports this to github and the releases are taken down (and they'll block the whole repository, till you remove it). No-one wants that, and I'm sure you don't either.

I agree with OP, this has been long enough. In the early days it was a checkbox if you wanted this crap, now it's impossible to find. 

You *do* control *that* there are ads in the installer at all. Just bundle the exe in an installer without malware/adware/other cruft. It's not hard.

**Comment by Hanif1601** [comment]
> _I don't control which advertisers are being shown to you_

Man, please remove that because it contains malware! Please, **for love of God**.

**Comment by TheRealDadbeard** [comment]
Idk but hiding the opt out seems highly illegal at least here in germany. I was super confused as how to opt out and after finding out that I had to click on this small little test I was just shaking my head.

You should remove that ASAP and distance yourself as far as possible because I already see this getting some hot attention.

**Comment by Hanif1601** [comment]
**Note for new users or user complaining about this issue:**
If you want to install this program, please disconnect your Internet connection temporary for the installer only. That's the only way to install Cheat Engine without any bloatware or adware while installing this program.

**Comment by cmonacaps** [comment]
it's similar to google adsense but ~~then for applications~~ may sometimes install mysterious daemon processes with admin privileges on your PC

**Comment by FransBouma** [comment]
You can also use this installer: https://www.cheatengine.org/download/CheatEngine68.3_MissingSetup.rar
which doesn't contain the malware.

**Comment by HylianLZ** [comment]
It's really not that difficult to pay attention to what you install. Quit whining and stop being lazy. Hundreds of thousands of installers have "additional software". Deal with it.

**Comment by Hanif1601** [comment]
> _It's really not that difficult to pay attention to what you install. Quit whining and stop being lazy._
Are you f*cking serious dude?! They're malware dude, they're damaging our Windows installation on our PC. **This is serious issue dude, not kidding at all.**

**Comment by Lightningreed** [comment]
The installer itself is not malicious, it's the ads which DB doesn't have control over. Like HylianZ, paying some attention is not that hard.

**Comment by Lightningreed** [comment]
Just to add a bit of detail, personally I have no problem installing CE, instructions are in English, and even that too. Talking about that, do you even read license?

**Comment by Lightningreed** [comment]
Furthermore, if CE installer WERE malicious, you would have gotten a warning from your downloader, and even if you access your anti-virus would YEET it asap.

**Comment by FransBouma** [comment]
@Lightningreed easy to say that, but it's not that easy if you make a mistake and your PC is ruined. Are you going to re-install windows for these people? Ah of course, they shouldn't be that stupid, right? Well, it might be you next time who makes a tiny mistake and then you wonder why you had to use this terrible installer. 

In this particular example it's not a checkbox that's checked by default to install something, it's a link in a different language you have to click which is totally not obvious. 

I really don't see how this needs any defending. It's malicious, it's vile and it's tiresome.

**Comment by Hanif1601** [comment]
> _easy to say that, but it's not that easy if you make a mistake and your PC is ruined. Are you going to re-install windows for these people? Ah of course, they shouldn't be that stupid, right? Well, it might be you next time who makes a tiny mistake and then you wonder why you had to use this terrible installer._

I agree with this. Because most people didn't realize if that malware or not (even they didn't have third party antivirus). Not all people are stupid in computing world.

**Comment by Naddox** [comment]
You can choose to use a different installer that doesn't package malware into it. The fact you dont care is just complete bullshit. I bet you would care if everyone just stopping using it all together.

**Comment by cheat-engine** [comment]
My contact at ironsrc has informed me that they have removed Segurazo from showing in the installer and will perform a compliance check

**Comment by Hanif1601** [comment]
@cheat-engine Well, that's the good news. If that completely removed from the installer, everyone won't complain like this. If not, try using different installer instead.

**Comment by Melvasul** [comment]
Why not removing any ad from the installer and leaving the option to money support you? 
I've used your software for years(game dev, dev, game modding) I will gladly gave you money :)

**Comment by Lightningreed** [comment]
@Melvasul Well, the fact is, not everyone can. While you can, I can't for example. Ads is the only way to support the dev for me, and I wouldn't mind taking more attention to support him.

**Comment by Hanif1601** [comment]
@Lightningreed Not always to support the developer itself. But the problem is the installer itself. Of course supporting the developer, but **not like that strategy**. Sometimes they make Patreon for donating or supporting the developer itself.

**Comment by Symbai** [comment]
> 
> 
> Why not removing any ad from the installer and leaving the option to money support you?
> I've used your software for years(game dev, dev, game modding) I will gladly gave you money :)

You can already: https://cheatengine.org/contribute.php and there is always an installer/adware-free download of the latest release as well https://cheatengine.org/download/CheatEngine68.3_MissingSetup.rar which can be found at https://cheatengine.org/downloads.php

**Comment by CheatEngineUser** [comment]
too many incel attaking dark byte here because they hate wemon!

**Comment by fade2gray** [comment]
Found at https://www.cheatengine.org/downloads.php

![No Installer](https://lh3.googleusercontent.com/LTspaQRudSiQ0T0hgKawW_7AAa-sovEJAEV4VVBuCoAYQiaKnRoCQhsfNF51R6Npxo7QcbOypA4PgHJsdeXH6QxwqUikeO221RDSQ2D9GqZG4kubMhjfdAW6o0xGyn4DcBzHDBP5Bg=w2400)

**Comment by fade2gray** [comment]
@Hanif1601 said ...
> 
> 
> **Please stop spreading malware on your installer, dev**. This is really important for average users or consumer.

Why would 'average users' want to use CE?

**Comment by Lightningreed** [comment]
> @Hanif1601 said ...
> 
> > **Please stop spreading malware on your installer, dev**. This is really important for average users or consumer.
> 
> Why would 'average users' want to use CE?

They can still simply use the next scan function to cheat some stuff. It's "not" that hard.

**Comment by Whitak3r** [comment]
Is there an option to download just a portable version? I'd like to just download an archive of cheat engine and extract it and run. It's a win win that way. Don't have to opt out and I can throw it on a flash drive n take it wherever.

**Comment by FreeER** [comment]
> Is there an option to download just a portable version? I'd like to just download an archive of cheat engine and extract it and run. It's a win win that way. Don't have to opt out and I can throw it on a flash drive n take it wherever.
https://github.com/cheat-engine/cheat-engine/issues/816#issuecomment-519042358

It's always been there, people just don't bother to read...

**Comment by fade2gray** [comment]
For crying-out-loud - if you want the 'portable' version which doesn't need an installer, go to the downloads page and read everything until you find "**For those who want to have Cheat Engine without automated installer** ..." then click on "**click here**" - IT ISN'T DIFFICULT!!!

**Comment by CheatEngineUser** [comment]
> For crying-out-loud - if you want the 'portable' version which doesn't need an installer, go to the downloads page and read everything until you find "**For those who want to have Cheat Engine without automated installer** ..." then click on "**click here**" - IT ISN'T DIFFICULT!!!

most people here are people who hates cheat engine and dark byter! no points waste energys on them

**Comment by cronack1** [comment]
This Segurazo malware fucked up my machine crashing various programs and terribly reducing stability. It took me way too long to remove and it probably mined my data, which would explain the recent influx of my accounts being hacked. I thought Malwarebytes cleaned the whole thing up when I dealt with it a month ago, but it was back today and took control of my Windows Defender. I had to edit the registry to access my virus protection settings.

Dev, this isn't a joke. By not inspecting your own installer and PUPs, **you are selling the identities of your consumers and compromising their livelihoods.** Your work is basically ruining people's lives.

You say you've contacted someone about it; okay, but why would you go to a malware distributor for non-malware? You need a new sponsor that is more honest and less malicious. Why not find a place that pays you for text ads and links that go in the installer without adding programs. Even the PUPs that add shitty toolbars to the browser aren't that bad. Just run your installer through a virus scan before you publish it.

Your community has lost all respect for you for this. Which is a shame, because you make great, popular software. Well, _made_. I'm never installing Cheat Engine again.

**Comment by cheat-engine** [comment]
1I have tested Segurazo myself and it worked as expected.
It actually blocked a virus i tested with.

Also the uninstaller functions as it should (in windows settings run the uninstaller for it) and afterwards it isn't blockijg anything anymore and the ststem functionsbas it should (do a proper reboot afterwards)

Just don't delete random files you think are related as that will break the uninstaller and will likely trigger the anti virus defenses against viruses that tamper with it

-
So i have to say that Segurazo is not malware but an actual anti virus.

**Comment by TheRealDadbeard** [comment]
Ehm it's known to send false positives to make you buy the full version. I can't believe you fall for that holy shit. Add that to the super tiny opt out option is a massive super big red flag to stay faaaaaar away from it and this installer. 

How you can even defend that is beyond me. So many people having issues with it completely removing as it behaves like malware.... Because it is. 

Get rid of it like ASAP. People do not use the installer or this piece of software. It contains malware.

**Comment by fade2gray** [comment]
Regarding the removal of 'Segurazo', I found this reddit ...

https://www.reddit.com/r/AskTechnology/comments/apjrwc/cant_uninstall_segurazo/

> I'm in no way official tech support, just someone who's been dealing with the same issue the last couple of days and was just able to get it uninstalled. For reference, I have a PC with Windows 10.
> 
> settings>apps>apps &features>Scroll down to the app list and hit uninstall when you see Segurazo
> 
> I clicked "yes" when it asked to grant permission (otherwise the uninstall option didn't show up). A Segurazo box came up and I hit "uninstall", but then another box asked if I was sure with a "yes" or "no", but I could only actually select "no". The "no" had a countdown that made it seem like it would automatically select "no" for you if you waited, but once the time runs down the "yes" button could be selected and it let me uninstall it. I had to restart my computer and a survey about the app showed up when I got back on. I just closed it out and double checked it was no longer showing up in my apps... So far, so good. As an FYI, I had to uninstall at least 3-4 other "anti-virus" programs that showed up around the same time that each had some kind of gimmicky way to get them uninstalled. Good Luck!

**Comment by Whoops-all-chaingunners** [comment]
I have been infested with something called Yahoo search engine. Every browser uses it now this is an outrage.

**Comment by fade2gray** [comment]
@Whoops-all-chaingunners This is what happens when people blindly click through installers without paying attention. Be outraged at yourself for being so blinkered.

**Comment by BlitzBanana** [comment]
@fade2gray @cheat-engine 	

- Install a malware BY DEFAULT on the end user's computer
- Blame the user because he used the default parameters
- Be totally fine with it as long as it brings you some money

Yeah good job !

You could at least be honest about what you're doing.

**Comment by FreeER** [comment]
To be fair it's more annoyware than malware and it's pretty much trivial to reinstall an OS now days especially with cheap external drives and cloud services and free automated backup systems even if it was actually harder to remove (though short of ransomware).

Also, it's far better to learn not to trust anything from these little things than from ones that actually matter.

Sure, it is _nice_ for the user to be able to click through and not care, but that's not realistic for life in general so anyone getting that upset about it just seems a bit immature to me. It just makes me think of some young person complaining about how they got conned into something and lost their money, yeah it sucks but at the same time it's pretty obvious that prince in Africa isn't desperate to send you his money, and that car dealership is going to upsale you on vehicles and additional features, and those interest rates are high etc. Realize this is always something you should watch out for just like agreeing to any contracts and EULAs that you aren't reading and don't know what you're accepting and move on with your newly obtained knowledge of life.

**Comment by BlitzBanana** [comment]
> Also, it's far better to learn not to trust anything from these little things than from ones that actually matter.

You will hide behind this, really ?

I didn't even lauched the installer since I'm using virustotal.com before any install.
But for others who have been affected, that's completley **unethical**.

As a developer that publish public software you have some responsibilities.

**Comment by FreeER** [comment]
> As a developer that publish public software you have some responsibilities.

I'm not the developer, I'm someone who uses the installer every time and haven't had an issue because I read the damn thing.

**Comment by BlitzBanana** [comment]
My comments was obviously turned against the peoples behind the cheat-engine code...
![image](https://user-images.githubusercontent.com/6515339/63205082-8417dc00-c09f-11e9-927d-9bf17c5a7c21.png)


But you're missing the hole point on purpose to not admit that what you do is dishonest.
I'm done, good continuation.

**Comment by FreeER** [comment]
yes, I have contributed some lua documentation https://github.com/cheat-engine/cheat-engine/commits?author=FreeER

Your whole point is omg this isn't 100% safe and you should be ashamed of being an insignificant part of that because you use an advertiser that has allowed malware into _their_ system.

My argument is that nothing is perfectly safe and you should always read every part of every installer and if you don't like that then spend the time to go to the download page and grab the non-installer version. It's not hard, on the other hand getting people to pay money can be especially if you don't _want_ to lock your work behind a paywall so that only people who are capable of paying can get access to it without breaking the law.

**Comment by BlitzBanana** [comment]
You're reading half of my answers, so I will allow myself to ignore the first part of you're which is irrelevant.

I got your point, but why don't you want to see the problem here ?
The developper could simply agree on changing the advertising provider for one who do not provide a way to malwares/adwares a growth vector instead of blaming the users for being "unable to read properly".

**Comment by FreeER** [comment]
How am I reading half of your "answer" when it's literally 2 lines and I responded to both?
>why don't you want to see the problem here ?
This assumes that you are correct in that there is an actual problem, but the literal answer to that obviously delves deeply into human psychology and my history, and I don't have the background to answer it. Of course it's easy to turn around and say why don't you see that it's not a problem? Especially for the dev considering that it's not costing them money if you choose not to use a program that you don't have to pay for.  The rest of that assumes that it actually is that easy and that anyone you pick won't introduce malware/adware shortly afterwards.

**Comment by BlitzBanana** [comment]
> How am I reading half of your "answer" when it's literally 2 lines and I responded to both?

You took the comments for yourself but I already explained that you were not targeted.

> The rest of that assumes that it actually is that easy and that anyone you pick won't introduce malware/adware shortly afterwards.

I didn't say that's easy, if it's not:
 - there could be at least a clear warning about that
 - you could stop blaming users

> This installer makes use of the installcore software recomendation pluginNote: Some anti-virus programs mistakenly pick up parts of Cheat Engine as a trojan/virus. If encountering trouble while installing, or cheat engine is not functional, disable your anti-virus before installing or running Cheat Engine(More info on this particular problem can be found here)

What about something clearly visible:

> Our installer uses an advertisment provider wich could push you to install an **adware**. Make sure to discard it explicitly if needed.

Again, making something for free does not give you the right to threaten user's data security, even indirectly.

**Comment by FreeER** [comment]
>You took the comments for yourself but I already explained that you were not targeted.

You quoted from me directly so... yes I was targeted, mis-targeted because github doesn't distinguish between someone with control over the project (at least assuming such people don't also get the Owner tag or equivalent...) and some random person who's had a couple small PRs accepted but targeted nevertheless.

>Our installer uses an advertisment provider wich could push you to install an adware. Make sure to discard it explicitly if needed.

sounds fair to me :) But it still puts the burden on the user to read something which they clearly are not doing very well so more of a blame shifting tactic than literally anything else lol. I suppose a better one would include an actual link to the installer free archive, which still requires reading but I suppose it might help those few people who stop when their av detects it and goes looking for more information/another download and come across it before they do any thing mentioning it elsewhere.

**Comment by BlitzBanana** [comment]
> You quoted from me directly so... yes I was targeted

I'm sorry, I thought it was obvious.

> sounds fair to me :) But it still puts the burden on the user to read something which they clearly are not doing very well

Yes sadly, but if the ad-provider cannot be changed, it seems the least of it.
If it's clearly visible (and short), at least the user will be warned.

**Comment by Whoops-all-chaingunners** [comment]
I got some free moldy bread. It is really good bread as long as you eat around the mold. I wasn't told about the mold until I took a bite. Never trust bakers.

**Comment by fade2gray** [comment]
@Whoops-all-chaingunners 
> 
> 
> I got some free moldy bread. It is really good bread as long as you eat around the mold. I wasn't told about the mold until I took a bite. Never trust bakers.

That has to be the worst analogy I have ever read - for a start, most bread is made using yeast which is a type of mold in itself.

If you were blind you wouldn't even have noticed the mold, but you're not, you just couldn't be bothered to pay attention to the installer.

**Comment by cronack1** [comment]
> I got some free moldy bread. It is really good bread as long as you eat around the mold. I wasn't told about the mold until I took a bite. Never trust bakers.

This is actually a great analogy. It's not legally advisable for any restaurant to give away expired food. If a bakery employee started handing out food that was moldy (hopefully I don't need to explain the usage of the word "moldy" to you) the bakery would end up sued. The employee would be fired. 

That could happen to you if a developer lost expensive work on an project because they used your software. This seems especially plausible since your Potentially Unwanted Malware crashed all of my open programs, and many of the functions of my PC were greatly inhibited until I removed it. You seem to have no idea what the software actually DOES, meaning it could be mining and selling developer data worth a lot of money. If this was tracked by someone with the resources, you're an accomplice, a careless dev who doesn't care what happens to his users because he thinks that they are stupid. I'm no lawyer, so maybe you won't be liable. Maybe you'll just be a shitty person who doesn't care if they help to potentially destroy lives of other developers. Maybe you'll be in the news and never find decent software work again.

I've installed thousands of programs in my life, and I spent my childhood on my computer. I never miss a beat when I check for PUPs and viruses, especially from non-reputable sources. I read the language of your installer VERY carefully, and I was especially focused because it was offering me Segurazo. I am 100% certain that I opted out of every single PUP, but they just installed anyway. Thus, your argument that "you guys don't know how to read" ("you're just fucking stupid") is moot. You're doing a great job of losing all of the respect that anybody in this community ever had for you.

Everyone got Segurazo and Chromium. As I understand it, Chromium is open source and this specific browser that was installed on my machine could've been modified to execute malicious scripts, such as installing more harmful PUPs/adware/malware/spyware/ransomware. When are you going to explain what this Chromium build does? Have you even tested it? What good reason could there possibly be for a modified web browser to come with a totally unrelated installer?

**Comment by cronack1** [comment]
Weird how "CheatEngineUser" has added "dislike" and "confused" reactions to every comment suggesting alternative payment methods or calling the dev out for being selfish

**Comment by fade2gray** [comment]
@cronack1 It's a misinformed analogy.
Do you even know what it is that you perceive to be mold? It is the spore releasing fruit bodies of fungi that are barely visible as threads of mycelia that invade the rest of its host, so nibbling 'safely' around the edges of your bread isn't doing you any better.

**Comment by fade2gray** [comment]
@cronack1 said ...
> 
> 
> Weird how "CheatEngineUser" has added "dislike" and "confused" reactions to every comment suggesting alternative payment methods or calling the dev out for being selfish

It doesn't take much to confuse _you_ ...


> 
> 
> @Hanif1601 said ...
> 
> > **Please stop spreading malware on your installer, dev**. This is really important for average users or consumer.
> 
> Why would 'average users' want to use CE?

**Comment by cronack1** [comment]
Are we seriously here to argue about mold, dude? Are we on a fucking culinary forum right now? Hilarious how you ignored all four paragraphs that I wrote to talk about mold. Ignoring the thickness of your skull, consider "bread-that-is-expired-and-will-make-you-sick". It is unethical to offer "free food" to people knowing that you will compromise their health. What's more, you were paid by someone who profits off of the eater's sickness. It's a good analogy, and shows that you are being _extremely_ selfish no matter how you look at it.

You should not sell the privacy and data security of your users. There is no defense for that, and it especially is unrelated to the composition of bread. 

- If Segurazo were really just an antivirus, why would it be free?

- You talked to your IronSource partners about removing it, so do you concede that Segurazo is malicious? 

- What does the Chromium build do, and have you tested it?

**Comment by dsasmblr** [comment]
**1**. Everyone gets the point. No matter who you are or where you stand.

**2**. DarkByte already said all he had to say about this. Also, he's been ardently outspoken in the past about not giving a hoot what people generally think about using CE. So, for better or for worse, take that as you will.

**3**. If all you want to do is bicker back and forth with one another at this point, can you do it outside of this? It seems any informative/productive discourse has gone out the window and now we're left with philosophical and loose legal meandering about moldy bread and software.

Again, this isn't steered towards any given person. This horse has just been beaten to death now and all sides that had anything actionable to say or do, have done so--save for the stragglers and end users with their subjective experiences that don't seem to be enriching one anothers'.

**Comment by fade2gray** [comment]
@cronack1 

> Are we seriously here to argue about mold, dude? Are we on a fucking culinary forum right now? 

A moot point as you already contributed to the argument, and resorting to profane and derogatory comments just reinforces your propensity for being stupid.

> If Segurazo were really just an antivirus, why would it be free?

I use a free security suite; it is extremely effective.

> You talked to your IronSource partners about removing it, so do you concede that Segurazo is malicious?
> What does the Chromium build do, and have you tested it?

I have nothing to do with CE's development; I'm just an end-user who can spot an 'opt-out' choice in an installer.

**Comment by e-l-y-c-k-ir** [comment]
> **Note for new users or user complaining about this issue:**
> If you want to install this program, please disconnect your Internet connection temporary for the installer only. That's the only way to install Cheat Engine without any bloatware or adware while running the installer itself.

@Hanif1601 
Thanks. Your workaround worked.

**Comment by Hanif1601** [comment]
@e-l-y-c-k-ir You're welcome, my dude. ;)

**Comment by davidrock** [comment]
The problem is that we don't have a clear way to DO NOT FUCKING INSTALLING VIRUS together with CE. That is the problem and YOU KNOW THAT.

**Comment by davidrock** [comment]
> @cronack1
> 
> I have nothing to do with CE's development; I'm just an end-user who can spot an 'opt-out' choice in an installer.

There is NO 'opt-out' choice anymore.

**Comment by HugoZink** [comment]
@cheat-engine you said it's fine as long as you can opt-out, but there is no clearly visible opt-out button in the installer anymore.

Does that mean it's no longer fine and you'll be removing this malware? This is illegal in the EU.

**Comment by cheat-engine** [comment]
Press decline to opt-out 
![image](https://user-images.githubusercontent.com/12006555/102525402-7c54b700-409a-11eb-904e-0e2a18e18872.png)

**Comment by dsasmblr** [comment]
I think this is more along the lines of HugoZink is expecting:

![correction](https://user-images.githubusercontent.com/22781064/102526354-86aa8d00-4069-11eb-80f0-8279078ac1df.png)

**Comment by GH-Rake** [comment]
my wife found porn on my laptop because of your shitty bundleware!!11

wtff guyzzzzzzzzzzzzzz now im getting divorced and have to eat cheeese out of a spray can in my moms basement for the rest of my life

thanks cheat machine, you are the big suck

i am calling polis

**Comment by fade2gray** [comment]
🤣

**Comment by Leak3611** [comment]
-rep, I am blind and installing malware

**Comment by KevinBlue18** [comment]
@fade2gray I agree with everything you said that people should read instead of randomly clicking.
> A moot point as you already contributed to the argument, and resorting to profane and derogatory comments just reinforces your propensity for being stupid.
But using doesn't mean someone is stupid but they should know when to use them. I remember reading Linus Torvalds old conversations in the Linux kernel mailing list with other developers that he tends to swear a lot when he needs to prove a point. [Here's a source of swearing meaning high intelligence.](https://www.sciencealert.com/swearing-is-a-sign-of-more-intelligence-not-less-say-scientists)

**Comment by fade2gray** [comment]
@KevinBlue18 
> Studies have shown, however, that swearing `MAY` in fact display a more, rather than less, intelligent use of language.

`Middle-FInger` 😁

**Comment by Whoops-all-chaingunners** [comment]
Why am I receiving a notice about being mentioned on this thread? Years
after commenting on it. Why is this still active there are clean installers
out there just Google it.

**Comment by imshirovich** [comment]
1. Download the clean installer from https://d2oq4dwfbh6gxl.cloudfront.net/f/CheatEngine/DOTPS-556/CheatEngine74.exe
2. Run it with the arguments: `/VERYSILENT /ZBDIST` something like:
```
c:\downloads\CheatEngine64.exe /VERYSILENT /ZBDIST
```
3. Enjoy

**Comment by KebabBurgerLover** [comment]
> I don't control which advertisers are being shown to you. Go to ironsource( https://www.ironsrc.com/ ) about any concerns you have regarding the companies they do business with. (it's similar to google adsense but then for applications)
> 
> as long as you can opt-out i have no problem with it.
> 
> (i have asked my contact person to investigate it)

Okay, Skill issue? It is your software.
