### ISSUE TITLE
lazarus 2.0.0 error

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#822]
postrings.LoadFromFile(filename, true);

C:\Users\Administrator\Desktop\fix-engine-master\Cheat Engine\LuaHandler.pas

LuaHandler.pas(8357,45) Error: Wrong number of parameters specified for call to "LoadFromFile"

LuaStrings.pas(220,63) Error: Wrong number of parameters specified for call to "LoadFromFile"

Error: Found declaration: LoadFromFile(const AnsiString);

Update to the latest Lazarus?

Error occurs at lazarus 2.0.0 

3.0.4 fpc

**Comment by cheat-engine** [comment]
I'm currently using a 3.2.0 snapshot.  remove the ,true part and it'll work

**Comment by mgrinzPlayer** [comment]
@DB, Which revision? Which branch? Will it be used for official release?

**Comment by cheat-engine** [comment]
lazarus 2.0.0
fpc 3.2.0 fixes branch (  3.2.0-beta-r42444 [2019/07/19] )

**Comment by JulianVolodia** [comment]
Seen the bug on latest stable release of Lazarus v2.0.4 r61665.
Workaround not works for that. It only leads to next errors on same reason.

![obraz](https://user-images.githubusercontent.com/1219023/65685640-b9cac000-e062-11e9-9a48-dd98a87b714d.png)

Merged PR #867 and later hotfix PR #913 not reference Lazarus with FPC version which is needed to compile.

Here they are - beta versions of Lazarus (lastest is now 2.0.4 r61665 - mentioned below are beta revision 61666) with FPC 3.2.0.
For Windows 32-bit:  https://sourceforge.net/projects/lazarus-snapshots/files/Window%2032/lazarus-2.0.4-61666-fpc-3.2.0-beta-42593/
For Windows 64-bit: https://sourceforge.net/projects/lazarus-snapshots/files/Window%2064/lazarus-2.0.4-61666-fpc-3.2.0-beta-42593/

**Conclusions**
Development of CheatEngine could help with Lazarus testing if they use that beta version. Proposing the change in README from lastest to beta-lastest.

**Comment by mgrinzPlayer** [comment]
If you want to send PR to CE project, it is recommended to use the very same FPC and Lazarus version. In this case the same source files from FPC project and same source files from Lazarus project.

DarkByte is using official Lazarus 2.0.0 (SVN tag is lazarus_2_0_0) and FPC from branch fixes_3_2 revision 42444. Official Lazarus 2.0.0 has older FPC, you have to set paths to newer FPC and FPC source, then you have to rebuild Lazarus, preferably with "clean all" option selected.

Currently I'm working on [CheatEngineUpDeluxe](https://github.com/mgrinzPlayer/CheatEngineUpDeluxe) project. It's just simple cmd file. You can easily setup the same enviroment I and DarkByte have. At least with the same Lazarus/FPC source files.

You can build cheatengine-i386.exe, cheatengine-x86_64.exe and of course other projects written in ObjectPascal (e.g. speedhack and VEHDebug).

**Comment by JulianVolodia** [comment]
> If you want to send PR to CE project, it is recommended to use the very same FPC and Lazarus version. In this case the same source files from FPC project and same source files from Lazarus project.

@mgrinzPlayer isn't it a good practice to use very same version?

I just show that workaround not working and *very same* version of IDE Env (with fpc) which do the thing isn't the *proposed in README* version.

Just it.

---
I do not understand rest of your thoughts and desires. How your another project/dev set/VM/app/pet influence or affect this one? Just chop work and we could do sth. I don't want to mess things.

Need some more time to diff CheatEngineUpDeluxe. Is there any TL;DR info what is better to use this UpDeluxe? Or is it only the launcher?

Kind regards.

**Comment by mgrinzPlayer** [comment]
I wrote: "If you want to send PR to CE project, it is recommended to use the very same FPC and Lazarus version."

I think I should be more precise. Sorry about that. I didn't meant PR about readme. I meant PR in general. Those with fixes, new features, etc. Using the same FPC/Lazarus version, the one used by the CE developer, will produce better, human readable SVN/GIT commits, you will be sure that your PR will work the same on his machine. Your code could work on lazarus-2.0.2 but not on lazarus-2.0.0.

And current CE release is compiled with:
> lazarus 2.0.0
> fpc 3.2.0 fixes branch ( 3.2.0-beta-r42444 [2019/07/19] )

You can get those specific FPC and Lazarus with TortoiseSVN (SlikSVN) from official sources:
- https://svn.freepascal.org/svn/fpc
- https://svn.freepascal.org/svn/lazarus

Then you have to compile it yourself with: GNU tools and bootstrap freepascal compiler.

You can also get those specific versions with FPCUpDeluxe if you setup it correctly. Or with my project CheatEngineUpDeluxe which I published recently on GitHub.

By the way, in the past DarkByte (before CheatEngine7.0 and CE6.8.x) uploaded his enviroment (Lazarus + FPC) which also were downloaded with SVN client (or FPCUp), then patched and compiled on his machine. You had to get that specific FPC/Lazarus version to compile CE without errors and without irritating CE behavior caused by bugs in official Lazarus release. It happened few times - I mean "patched FPC with patched Lazarus" enviroment, not a snapshot nor a beta nor official Lazarus release from official https://www.lazarus-ide.org



It is possible to compile "with newer Lazarus with older FPC" but you have to edit source files many times. Steps would be: do a "clean build", edit lines with compile errors, do a "clean build", .... until it compiles without errors.

**Comment by mgrinzPlayer** [comment]
I agree that current readme "Build Instructions" is not quite clear.

What you think about this, more or less:


#  Build Instructions
1. Official CE7.0 was compiled with official Lazarus 2.0.0 with FPC updated to beta version 3.2.0 (from SVN, branch "fixes_3_2" revision 42444). If you want to have build enviroment as similar as possible to the one used to compile official CE 7.0, you'll have to compile the environment yourself.
Some links:
https://wiki.lazarus.freepascal.org/Getting_Lazarus
https://wiki.lazarus.freepascal.org/Installing_Lazarus
https://www.freepascal.org/develop.html
You can also use third party tools such as [fpcupdeluxe](https://github.com/mgrinzPlayer/CheatEngineUpDeluxe) or [CheatEngineUpDeluxe](https://github.com/mgrinzPlayer/CheatEngineUpDeluxe) to automate it.
Or you can try your luck with latest Lazarus releases or snapshots. Probably you will need edit a few/dozen files to successfully compile CE project.

**Comment by JulianVolodia** [comment]
@mgrinzPlayer thanks for support and this care for clerance. All is OK, one sec. I won't be offensive, but I feel like I was/am so sorry for that. Bad day.

Hmm, but I have no problem with compilation. It wasn't problematic at all. Just this is not truth that lastest release of Lazarus will compile CheatEngine. Moreover, I wrote that mentioned workaround isn't fix that for anybody for some time (while fpc 3.2.0 still in lazarus-beta snapshots).

Just have very small idea to change README to use lazarus-snapshot instead of lazarus release now. Last will make only confuse for somebody who want to use it. First work fine (compile win32,win64, debug same). No need to get this svn environment.

Before somebody make contribution, there is a huge way from building and contributing. Just check README and follow steps to give small feedback. 

I choosen this issue cause it is connected via PR #867 to PR #913 which was one last touching place where lastest Lazarus is pointed to be in build secion of README. Here also was mentioned fix to remove ', true' from code as a workaround. Just want give small contribution.

I think what you proposed is ok for more advanced section 'Contribution' or 'Contribution in codebase & release prepare' section. Which is quite hermetic.
CE is nice tool and many ppl use that without compiling on themself.

Thanks for your care. Could I help you with sth, mostly with C++ dev?

**Comment by mgrinzPlayer** [comment]
Funny thing. I've just tried Lazarus v2.0.4 r61665 (lazarus-2.0.4-61666-fpc-3.2.0-beta-42593-win64.exe and lazarus-2.0.4-61666-fpc-3.2.0-beta-42593-cross-i386-win32-win64.exe) and [current](https://github.com/cheat-engine/cheat-engine/commit/e694b05cf308cb749abd19dab45ee4236dd04470) CE source code. CE 32bit and 64bit compiled successfully without workarounds/patching.

Did you have a clean CE source? Did you use "Run -> Clean up and Build" in Lazarus?

**Comment by JulianVolodia** [comment]
@mgrinzPlayer przepraszam, ale to zrobię. Napiszę po polsku.

Co się stało? Czy czytałeś mój komentarz? Czemu szukasz u mnie błędu? <ocenzurowane_jedno_zdanie>
Ja podreślam cały czas że nie mam problemu tylko w README nie dalej niż miesiąc temu była poprawka z wersji 2.0.0 na lastest z Lazarus'a - stabilne wydanie, gdzie fpc jest w wersji 3.0.4. Która uniemożliwia budowanie. Podałem w komentarzu wszystko.

Lazarus-snapshot jest z 3.2.0 i jak byłby update, to lastest stamtąd byłby również z nim (zgodnie z zasadą niemrożenia zależności).

![obraz](https://user-images.githubusercontent.com/1219023/65725758-b7448680-e0b3-11e9-88eb-3bcb1cf4259f.png)

![obraz](https://user-images.githubusercontent.com/1219023/65725692-8cf2c900-e0b3-11e9-9042-4907831943db.png)

Co się dzieje? O co Ci chodzi?

**Comment by JulianVolodia** [comment]
Pytasz, czy mam czysty wierzchołek mastera Cheat Engine, pytasz czy postąpiłem jedną ze znanych metod. 3 raz tłumaczę, że nie mam problemu tylko info w README jest błędne.
Nie uważam że trzeba tam opisywać to co mi tłumaczyłeś, z 2,5 GB-wym blob'em którego nie potrzebuję jak zresztą inni, bo nie robią release'u. Jeżeli by mieli, to pewnie by o to dbali.

Chodzi **wyłącznie o to** że w README jest podana błędna instrukcja. Rozumiemy się?

---
In English, @mgrinzPlayer sorry but I bet you don't read my first comment. Return and see this. I just point a need to change in README.

(yes, Polish is funny and flowery language.)

**Comment by JulianVolodia** [comment]
> 
> 
> Oh, luz, przeoczyłem wyraz "stable" w twoim pierwszym komentarzu.

@mgrinzPlayer 
Sobie wyjaśniliśmy w końcu, stable było nadmiarowe. Beta to nie release'y - to też tam napisałem.

cheers, usuwam tę g*burzę. 

Uważasz że dobrze by tak było żeby ludzie przypadkowi (hmm, głównie zjadacze chleba nie znający dobrze RE chyba...) mieli beta-wersję. Czy jakąś dyskusję zaczynać o tym co wrzucić w README?
Fajny projekt, a mam chwilę i chciałbym mu poświęcić.

**Comment by JulianVolodia** [comment]
@mgrinzPlayer pytałem o tę wersję release'u DarkByte'a gdyż chciałem wiedzieć czy ma jakieś pomysły na wrzucenie tego info, guideline na przyszłość, po prostu dla dokumentacji. Napisał tam 'will' a nigdzie nie znalazłem info z czego był budowany release. Stąd pytanie.

Eh, mówiłem że dzisiaj nie mój dzień.

**Comment by mgrinzPlayer** [comment]
Takie informacje pojawiają się to tu to tam. Na oficjalnym forum CE w jakimś wątku w dziale "Cheat Engine Source" bądź ukrytym dziale "Cheat Engine Beta", czasami w dowolnym innym wątku, gdy ktoś napisze, że ma taki czy inny problem z CE bądź kompilacją tegoż.

CE6.80 pojawił się 20.08.2019, od tamtej pory DB nie wspomniał o żadnych innych wersjach Laz/FPC, ani na forum, ani tu, ani na Discord. Są już trzy issues, w których napisałem o Laz2.0.0 i FPC z gałęzi fixes_3_2 rewizja 42444. Nie zdementował.

Dodatkowo, gdy CE7.0 był wypuszczany w fazie alfa, beta oraz release candidate, zawartość ostatnio modyfikowanych plików LFM sugerowała, że to dalej Lazarus 2.0.0. Sprawdź historię pliku MainUnit.lfm. Był niedawno modyfikowany, pewnie przypadkowo, przez autora. Pozmieniały się niektóre wartości w Left, Top, ale LCLVersion to dalej 2.0.0.4 (wersja LCL jest ta sama co Lazarusa - [link](https://github.com/graemeg/lazarus/blob/upstream/lcl/lclversion.pas#L41-L46))

W kilku ostatnio modyfikowanych LFM znajdziesz 2.0.4.0, ale to wynika z tego, że ktoś pracował na nowszym i wysłał takiego PR.

Co do sensowności istnienia mojego "bloba"... Były już takie przypadki:
- https://forum.cheatengine.org/viewtopic.php?p=5523518#5523518
- około 5 lat temu, tu [link](https://forum.cheatengine.org/viewtopic.php?p=5536858#5536858), sugerował użycie FPCUp. (FPCUpDeluxe to następca FPCUp)
- CE 6.8.x, Lazarus rewizja X sprzed pół roku, FPC rewizja Y sprzed roku czy dwóch, połatane za pomocą łat, które trafiły do trunk w ostatnim miesiącu/tygodniu.
- dwa razy DB wrzucił skompresowane archiwizerem całe środowisko, które miał na dysku.
- no i obecna sytuacja. Autor zdecydował się na kolejnego potwora Frankensteina :) Dlatego sądzę, że najlepiej używać dokładnie tego samego, a przynajmniej coś najbardziej podobnego, co autor.

Wykorzystywanie takich eksperymentalnych tworów to jego specjalność. Dlatego zdecydowałem się na ten prosty cmd w CheatEngineUpDeluxe. Aby przygotować się na kolejne wersje/ewentualne wymagane patche do FPC lub Laz, bądź obu naraz.

Z tego co zaobserwowałem z ostatnich lat zwykli zjadacze chleba, paradoksalnie, będą mieli mniej problemów, gdy będą używać tę samą wersję, takiego bloba przygotowanego przez DB czy mnie.

To zaawansowani mogą bawić się w instalowanie innych wersji, nieważne jakich: release, beta, czy z pobranych z SVN/Git z trunk/master.

Dobra, pewnie ktoś się wkurzy za offtop.

**Comment by JulianVolodia** [comment]
> Dobra, pewnie ktoś się wkurzy za offtop.

Teraz gadamy, poświęciłem już na to czas to cóż. Wcześniej serio nie rozumiałem co się dzieje bo chciałem uprościć rzeczy. Ale trochę popłynęliśmy ;)

Jak dla mnie możemy usunąć wiadomości i po sprawie? :)

**Comment by mgrinzPlayer** [comment]
Czy na tym tworze co używa DB wszystko działa poprawnie... tego nigdy nie możemy być w 100% pewni.

**Comment by mgrinzPlayer** [comment]
W ogóle Lazarus/FPC to trochę taka niewiadoma, wystarczy co jakiś czas zobaczyć co pojawia się na oficjalnym Bug Tracker...

Tak, myślę, że możemy kasować. Co do tego nieszczęsnego readme

**Comment by mgrinzPlayer** [comment]
JulianVolodia and I have deleted some messages, we are sorry that we were off topic
